import type { AdminHomePayload } from './api';

/** Deterministic fixture for gallery / screenshot states. */
export const adminHomeSuccessFixture: AdminHomePayload = {
  newOrders: 24,
  ordersInProduction: 18,
  ordersNearingDelivery: 11,
  completedOrders: 40,
  delayedOrders: 7,
  openInvoices: 8,
  outstandingReceivables: 32650,
  dealersActive: 14,
  pendingReturns: 1,
  lowStockItems: 23,
  recentOrders: [
    {
      id: 'so1',
      number: 'ORD-1258',
      status: 'IN_PRODUCTION',
      title: 'Lobby Sofa',
      imageUrl: null,
      customerName: 'Ahmed Traders',
      externalOrderNumber: null,
      endCustomerName: null,
      requiredDeliveryDate: '2026-08-01T00:00:00.000Z',
    },
    {
      id: 'so2',
      number: 'ORD-1260',
      status: 'READY_FOR_DELIVERY',
      title: 'Dining Set',
      imageUrl: null,
      customerName: 'Nile Interiors',
      externalOrderNumber: null,
      endCustomerName: null,
      requiredDeliveryDate: '2026-08-08T00:00:00.000Z',
    },
    {
      id: 'so3',
      number: 'ORD-1261',
      status: 'DELIVERED',
      title: 'Office Desk',
      imageUrl: null,
      customerName: 'Oasis Living',
      externalOrderNumber: null,
      endCustomerName: null,
      requiredDeliveryDate: null,
    },
  ],
  floorSpotlight: {
    reason: 'late',
    peerCount: 7,
    order: {
      id: 'so1',
      number: 'ORD-1258',
      status: 'IN_PRODUCTION',
      title: 'Lobby Sofa',
      imageUrl: null,
      customerName: 'Ahmed Traders',
      externalOrderNumber: null,
      endCustomerName: null,
      requiredDeliveryDate: '2026-08-01T00:00:00.000Z',
    },
  },
  generatedAt: '2026-08-05T12:00:00.000Z',
  completedToday: 6,
  urgentTasksCount: 2,
  urgentTasks: [
    {
      id: 't1',
      number: 'PT-1042',
      name: 'Upholstery — Nile sofa',
      priority: 'URGENT',
      status: 'IN_PROGRESS',
      plannedCompletion: null,
      assigneeName: 'Sara N.',
    },
    {
      id: 't2',
      number: 'PT-1043',
      name: 'Carpentry — Oasis chairs',
      priority: 'HIGH',
      status: 'READY',
      plannedCompletion: null,
      assigneeName: 'Omar K.',
    },
  ],
  unreadNotifications: 3,
  recentActivity: [
    {
      id: 'a1',
      action: 'SALES_ORDER_UPDATE',
      entityType: 'SalesOrder',
      entityId: 'so1',
      createdAt: '2026-08-05T09:30:00.000Z',
      actorName: 'System Admin',
    },
  ],
};

export const adminHomeEmptyFixture: AdminHomePayload = {
  ...adminHomeSuccessFixture,
  newOrders: 0,
  ordersInProduction: 0,
  ordersNearingDelivery: 0,
  delayedOrders: 0,
  pendingReturns: 0,
  lowStockItems: 0,
  outstandingReceivables: 0,
  completedToday: 0,
  urgentTasksCount: 0,
  urgentTasks: [],
  unreadNotifications: 0,
  recentOrders: [],
  floorSpotlight: null,
  recentActivity: [],
};
