export const PERMISSIONS = [
  'customer.read',
  'customer.create',
  'customer.update',
  'customer.delete',
  'contact.manage',
  'address.manage',
  'quotation.read',
  'quotation.create',
  'quotation.update',
  'quotation.submit',
  'quotation.approve',
  'quotation.send',
  'quotation.accept',
  'quotation.reject',
  'quotation.revise',
  'sales-order.read',
  'sales-order.create',
  'sales-order.update',
  'contract.read',
  'contract.manage',
  'supplier.read',
  'supplier.manage',
  'purchase-request.read',
  'purchase-request.create',
  'purchase-order.read',
  'purchase-order.create',
  'purchase-order.approve',
  'supplier-invoice.read',
  'supplier-invoice.create',
  'supplier-payment.record',
  'inventory.read',
  'inventory.receive',
  'inventory.issue',
  'inventory.transfer',
  'inventory.adjust',
  'inventory.count',
  'inventory.cost.read',
  'production-order.read',
  'production-order.create',
  'production-order.update',
  'production-order.assign',
  'production-task.read',
  'production-task.update-own',
  'production-task.update-any',
  'production-task.complete',
  'quality-inspection.read',
  'quality-inspection.perform',
  'quality-inspection.approve',
  'delivery.read',
  'delivery.update',
  'invoice.read',
  'invoice.create',
  'invoice.update',
  'payment.read',
  'payment.record',
  'statement.read',
  'report.sales.read',
  'report.production.read',
  'report.inventory.read',
  'report.financial.read',
  'user.manage',
  'role.manage',
  'settings.manage',
  'catalog.manage',
  'catalog.read',
  'department.manage',
  'warehouse.manage',
  'audit.read',
  'document.read',
  'document.manage',
  'ai-intake.read',
  'ai-intake.manage',
  'ai-chat.read',
  'notification.read',
  'request.read',
  'request.create',
  'request.update',
  'schedule.read',
  'schedule.manage',
  'schedule.approve',
  'schedule.override',
  'schedule.settings.manage',
  'schedule.capacity.read',
  'schedule.availability.own',
  'schedule.read.own',
  'schedule.request-change.own',
] as const;

export type Permission = (typeof PERMISSIONS)[number];

export const ROLES = [
  'CUSTOMER',
  'PRODUCTION_WORKER',
  'SYSTEM_ADMINISTRATOR',
] as const;

export type Role = (typeof ROLES)[number];

const p = {
  customerRead: 'customer.read',
  customerCreate: 'customer.create',
  customerUpdate: 'customer.update',
  customerDelete: 'customer.delete',
  contactManage: 'contact.manage',
  addressManage: 'address.manage',
  quotationRead: 'quotation.read',
  quotationCreate: 'quotation.create',
  quotationUpdate: 'quotation.update',
  quotationSubmit: 'quotation.submit',
  quotationApprove: 'quotation.approve',
  quotationSend: 'quotation.send',
  quotationAccept: 'quotation.accept',
  quotationReject: 'quotation.reject',
  quotationRevise: 'quotation.revise',
  salesOrderRead: 'sales-order.read',
  salesOrderCreate: 'sales-order.create',
  salesOrderUpdate: 'sales-order.update',
  contractRead: 'contract.read',
  contractManage: 'contract.manage',
  supplierRead: 'supplier.read',
  supplierManage: 'supplier.manage',
  purchaseRequestRead: 'purchase-request.read',
  purchaseRequestCreate: 'purchase-request.create',
  purchaseOrderRead: 'purchase-order.read',
  purchaseOrderCreate: 'purchase-order.create',
  purchaseOrderApprove: 'purchase-order.approve',
  supplierInvoiceRead: 'supplier-invoice.read',
  supplierInvoiceCreate: 'supplier-invoice.create',
  supplierPaymentRecord: 'supplier-payment.record',
  inventoryRead: 'inventory.read',
  inventoryReceive: 'inventory.receive',
  inventoryIssue: 'inventory.issue',
  inventoryTransfer: 'inventory.transfer',
  inventoryAdjust: 'inventory.adjust',
  inventoryCount: 'inventory.count',
  inventoryCostRead: 'inventory.cost.read',
  productionOrderRead: 'production-order.read',
  productionOrderCreate: 'production-order.create',
  productionOrderUpdate: 'production-order.update',
  productionOrderAssign: 'production-order.assign',
  productionTaskRead: 'production-task.read',
  productionTaskUpdateOwn: 'production-task.update-own',
  productionTaskUpdateAny: 'production-task.update-any',
  productionTaskComplete: 'production-task.complete',
  qualityInspectionRead: 'quality-inspection.read',
  qualityInspectionPerform: 'quality-inspection.perform',
  qualityInspectionApprove: 'quality-inspection.approve',
  deliveryRead: 'delivery.read',
  deliveryUpdate: 'delivery.update',
  invoiceRead: 'invoice.read',
  invoiceCreate: 'invoice.create',
  invoiceUpdate: 'invoice.update',
  paymentRead: 'payment.read',
  paymentRecord: 'payment.record',
  statementRead: 'statement.read',
  reportSalesRead: 'report.sales.read',
  reportProductionRead: 'report.production.read',
  reportInventoryRead: 'report.inventory.read',
  reportFinancialRead: 'report.financial.read',
  userManage: 'user.manage',
  roleManage: 'role.manage',
  settingsManage: 'settings.manage',
  catalogManage: 'catalog.manage',
  catalogRead: 'catalog.read',
  departmentManage: 'department.manage',
  warehouseManage: 'warehouse.manage',
  auditRead: 'audit.read',
  documentRead: 'document.read',
  documentManage: 'document.manage',
  aiIntakeRead: 'ai-intake.read',
  aiIntakeManage: 'ai-intake.manage',
  aiChatRead: 'ai-chat.read',
  notificationRead: 'notification.read',
  requestRead: 'request.read',
  requestCreate: 'request.create',
  requestUpdate: 'request.update',
  scheduleRead: 'schedule.read',
  scheduleManage: 'schedule.manage',
  scheduleApprove: 'schedule.approve',
  scheduleOverride: 'schedule.override',
  scheduleSettingsManage: 'schedule.settings.manage',
  scheduleCapacityRead: 'schedule.capacity.read',
  scheduleAvailabilityOwn: 'schedule.availability.own',
  scheduleReadOwn: 'schedule.read.own',
  scheduleRequestChangeOwn: 'schedule.request-change.own',
} as const satisfies Record<string, Permission>;

/** Default permission grants per role; row-level scoping enforced at the API layer. */
export const ROLE_PERMISSIONS: Record<Role, Permission[]> = {
  CUSTOMER: [
    p.customerRead,
    p.addressManage,
    p.catalogRead,
    p.quotationRead,
    p.quotationAccept,
    p.quotationReject,
    p.salesOrderRead,
    p.productionOrderRead,
    p.deliveryRead,
    p.contractRead,
    p.invoiceRead,
    p.paymentRead,
    p.statementRead,
    p.documentRead,
    p.documentManage,
    p.notificationRead,
    p.requestRead,
    p.requestCreate,
    p.requestUpdate,
    p.aiIntakeManage,
    p.aiChatRead,
    p.scheduleAvailabilityOwn,
    p.scheduleReadOwn,
    p.scheduleRequestChangeOwn,
  ],

  /** Floor worker — production tasks, quality, and delivery. */
  PRODUCTION_WORKER: [
    p.productionOrderRead,
    p.productionTaskRead,
    p.productionTaskUpdateOwn,
    p.productionTaskComplete,
    p.qualityInspectionRead,
    p.qualityInspectionPerform,
    p.qualityInspectionApprove,
    p.deliveryRead,
    p.deliveryUpdate,
    p.salesOrderRead,
    p.documentRead,
    p.documentManage,
    p.notificationRead,
  ],

  SYSTEM_ADMINISTRATOR: [...PERMISSIONS],
};
