export const PERMISSIONS = [
  'customer.read',
  'customer.create',
  'customer.update',
  'customer.delete',
  'contact.manage',
  'address.manage',
  'quotation.read',
  'quotation.create',
  'quotation.update',
  'quotation.submit',
  'quotation.approve',
  'quotation.send',
  'quotation.accept',
  'quotation.reject',
  'quotation.revise',
  'sales-order.read',
  'sales-order.create',
  'sales-order.update',
  'contract.read',
  'contract.manage',
  'supplier.read',
  'supplier.manage',
  'purchase-request.read',
  'purchase-request.create',
  'purchase-order.read',
  'purchase-order.create',
  'purchase-order.approve',
  'inventory.read',
  'inventory.receive',
  'inventory.issue',
  'inventory.transfer',
  'inventory.adjust',
  'inventory.count',
  'production-order.read',
  'production-order.create',
  'production-order.update',
  'production-order.assign',
  'production-task.read',
  'production-task.update-own',
  'production-task.update-any',
  'production-task.complete',
  'quality-inspection.read',
  'quality-inspection.perform',
  'quality-inspection.approve',
  'delivery.read',
  'delivery.update',
  'invoice.read',
  'invoice.create',
  'invoice.update',
  'payment.read',
  'payment.record',
  'statement.read',
  'report.sales.read',
  'report.production.read',
  'report.inventory.read',
  'report.financial.read',
  'user.manage',
  'role.manage',
  'settings.manage',
  'audit.read',
  'document.read',
  'document.manage',
  'ai-intake.read',
  'ai-intake.manage',
  'notification.read',
  'request.read',
  'request.create',
  'request.update',
] as const;

export type Permission = (typeof PERMISSIONS)[number];

export const ROLES = [
  'CUSTOMER',
  'SALES_REPRESENTATIVE',
  'SALES_MANAGER',
  'PURCHASING_EMPLOYEE',
  'PURCHASING_MANAGER',
  'WAREHOUSE_EMPLOYEE',
  'WAREHOUSE_MANAGER',
  'PRODUCTION_WORKER',
  'PRODUCTION_SUPERVISOR',
  'QUALITY_INSPECTOR',
  'DELIVERY_EMPLOYEE',
  'ACCOUNTANT',
  'FINANCE_MANAGER',
  'GENERAL_MANAGER',
  'SYSTEM_ADMINISTRATOR',
] as const;

export type Role = (typeof ROLES)[number];

const p = {
  customerRead: 'customer.read',
  customerCreate: 'customer.create',
  customerUpdate: 'customer.update',
  customerDelete: 'customer.delete',
  contactManage: 'contact.manage',
  addressManage: 'address.manage',
  quotationRead: 'quotation.read',
  quotationCreate: 'quotation.create',
  quotationUpdate: 'quotation.update',
  quotationSubmit: 'quotation.submit',
  quotationApprove: 'quotation.approve',
  quotationSend: 'quotation.send',
  quotationAccept: 'quotation.accept',
  quotationReject: 'quotation.reject',
  quotationRevise: 'quotation.revise',
  salesOrderRead: 'sales-order.read',
  salesOrderCreate: 'sales-order.create',
  salesOrderUpdate: 'sales-order.update',
  contractRead: 'contract.read',
  contractManage: 'contract.manage',
  supplierRead: 'supplier.read',
  supplierManage: 'supplier.manage',
  purchaseRequestRead: 'purchase-request.read',
  purchaseRequestCreate: 'purchase-request.create',
  purchaseOrderRead: 'purchase-order.read',
  purchaseOrderCreate: 'purchase-order.create',
  purchaseOrderApprove: 'purchase-order.approve',
  inventoryRead: 'inventory.read',
  inventoryReceive: 'inventory.receive',
  inventoryIssue: 'inventory.issue',
  inventoryTransfer: 'inventory.transfer',
  inventoryAdjust: 'inventory.adjust',
  inventoryCount: 'inventory.count',
  productionOrderRead: 'production-order.read',
  productionOrderCreate: 'production-order.create',
  productionOrderUpdate: 'production-order.update',
  productionOrderAssign: 'production-order.assign',
  productionTaskRead: 'production-task.read',
  productionTaskUpdateOwn: 'production-task.update-own',
  productionTaskUpdateAny: 'production-task.update-any',
  productionTaskComplete: 'production-task.complete',
  qualityInspectionRead: 'quality-inspection.read',
  qualityInspectionPerform: 'quality-inspection.perform',
  qualityInspectionApprove: 'quality-inspection.approve',
  deliveryRead: 'delivery.read',
  deliveryUpdate: 'delivery.update',
  invoiceRead: 'invoice.read',
  invoiceCreate: 'invoice.create',
  invoiceUpdate: 'invoice.update',
  paymentRead: 'payment.read',
  paymentRecord: 'payment.record',
  statementRead: 'statement.read',
  reportSalesRead: 'report.sales.read',
  reportProductionRead: 'report.production.read',
  reportInventoryRead: 'report.inventory.read',
  reportFinancialRead: 'report.financial.read',
  userManage: 'user.manage',
  roleManage: 'role.manage',
  settingsManage: 'settings.manage',
  auditRead: 'audit.read',
  documentRead: 'document.read',
  documentManage: 'document.manage',
  aiIntakeRead: 'ai-intake.read',
  aiIntakeManage: 'ai-intake.manage',
  notificationRead: 'notification.read',
  requestRead: 'request.read',
  requestCreate: 'request.create',
  requestUpdate: 'request.update',
} as const satisfies Record<string, Permission>;

/** Default permission grants per role; row-level scoping enforced at the API layer. */
export const ROLE_PERMISSIONS: Record<Role, Permission[]> = {
  CUSTOMER: [
    p.customerRead,
    p.quotationRead,
    p.quotationAccept,
    p.quotationReject,
    p.salesOrderRead,
    p.contractRead,
    p.invoiceRead,
    p.paymentRead,
    p.statementRead,
    p.documentRead,
    p.notificationRead,
    p.requestRead,
    p.requestCreate,
    p.requestUpdate,
  ],

  SALES_REPRESENTATIVE: [
    p.customerRead,
    p.customerCreate,
    p.customerUpdate,
    p.contactManage,
    p.addressManage,
    p.quotationRead,
    p.quotationCreate,
    p.quotationUpdate,
    p.quotationSubmit,
    p.salesOrderRead,
    p.contractRead,
    p.documentRead,
    p.documentManage,
    p.notificationRead,
    p.requestRead,
    p.requestCreate,
    p.requestUpdate,
    p.reportSalesRead,
  ],

  SALES_MANAGER: [
    p.customerRead,
    p.customerCreate,
    p.customerUpdate,
    p.customerDelete,
    p.contactManage,
    p.addressManage,
    p.quotationRead,
    p.quotationCreate,
    p.quotationUpdate,
    p.quotationSubmit,
    p.quotationApprove,
    p.quotationSend,
    p.quotationRevise,
    p.salesOrderRead,
    p.salesOrderCreate,
    p.salesOrderUpdate,
    p.contractRead,
    p.contractManage,
    p.documentRead,
    p.documentManage,
    p.notificationRead,
    p.requestRead,
    p.requestCreate,
    p.requestUpdate,
    p.reportSalesRead,
  ],

  PURCHASING_EMPLOYEE: [
    p.customerRead,
    p.supplierRead,
    p.purchaseRequestRead,
    p.purchaseRequestCreate,
    p.purchaseOrderRead,
    p.purchaseOrderCreate,
    p.inventoryRead,
    p.notificationRead,
  ],

  PURCHASING_MANAGER: [
    p.customerRead,
    p.supplierRead,
    p.supplierManage,
    p.purchaseRequestRead,
    p.purchaseRequestCreate,
    p.purchaseOrderRead,
    p.purchaseOrderCreate,
    p.purchaseOrderApprove,
    p.inventoryRead,
    p.reportInventoryRead,
    p.notificationRead,
  ],

  WAREHOUSE_EMPLOYEE: [
    p.inventoryRead,
    p.inventoryReceive,
    p.inventoryIssue,
    p.inventoryTransfer,
    p.inventoryCount,
    p.notificationRead,
  ],

  WAREHOUSE_MANAGER: [
    p.inventoryRead,
    p.inventoryReceive,
    p.inventoryIssue,
    p.inventoryTransfer,
    p.inventoryAdjust,
    p.inventoryCount,
    p.reportInventoryRead,
    p.notificationRead,
  ],

  PRODUCTION_WORKER: [
    p.productionOrderRead,
    p.productionTaskRead,
    p.productionTaskUpdateOwn,
    p.productionTaskComplete,
    p.notificationRead,
  ],

  PRODUCTION_SUPERVISOR: [
    p.productionOrderRead,
    p.productionOrderCreate,
    p.productionOrderUpdate,
    p.productionOrderAssign,
    p.productionTaskRead,
    p.productionTaskUpdateOwn,
    p.productionTaskUpdateAny,
    p.productionTaskComplete,
    p.qualityInspectionRead,
    p.reportProductionRead,
    p.notificationRead,
  ],

  QUALITY_INSPECTOR: [
    p.productionOrderRead,
    p.productionTaskRead,
    p.qualityInspectionRead,
    p.qualityInspectionPerform,
    p.qualityInspectionApprove,
    p.notificationRead,
  ],

  DELIVERY_EMPLOYEE: [
    p.deliveryRead,
    p.deliveryUpdate,
    p.salesOrderRead,
    p.documentRead,
    p.notificationRead,
  ],

  ACCOUNTANT: [
    p.customerRead,
    p.quotationRead,
    p.salesOrderRead,
    p.invoiceRead,
    p.invoiceCreate,
    p.invoiceUpdate,
    p.paymentRead,
    p.paymentRecord,
    p.statementRead,
    p.reportFinancialRead,
    p.documentRead,
    p.notificationRead,
  ],

  FINANCE_MANAGER: [
    p.customerRead,
    p.quotationRead,
    p.salesOrderRead,
    p.invoiceRead,
    p.invoiceCreate,
    p.invoiceUpdate,
    p.paymentRead,
    p.paymentRecord,
    p.statementRead,
    p.reportSalesRead,
    p.reportFinancialRead,
    p.documentRead,
    p.notificationRead,
  ],

  GENERAL_MANAGER: [
    p.customerRead,
    p.customerCreate,
    p.customerUpdate,
    p.customerDelete,
    p.contactManage,
    p.addressManage,
    p.quotationRead,
    p.quotationCreate,
    p.quotationUpdate,
    p.quotationSubmit,
    p.quotationApprove,
    p.quotationSend,
    p.quotationRevise,
    p.salesOrderRead,
    p.salesOrderCreate,
    p.salesOrderUpdate,
    p.contractRead,
    p.contractManage,
    p.supplierRead,
    p.supplierManage,
    p.purchaseRequestRead,
    p.purchaseRequestCreate,
    p.purchaseOrderRead,
    p.purchaseOrderCreate,
    p.purchaseOrderApprove,
    p.inventoryRead,
    p.inventoryReceive,
    p.inventoryIssue,
    p.inventoryTransfer,
    p.inventoryAdjust,
    p.inventoryCount,
    p.productionOrderRead,
    p.productionOrderCreate,
    p.productionOrderUpdate,
    p.productionOrderAssign,
    p.productionTaskRead,
    p.productionTaskUpdateOwn,
    p.productionTaskUpdateAny,
    p.productionTaskComplete,
    p.qualityInspectionRead,
    p.qualityInspectionPerform,
    p.qualityInspectionApprove,
    p.deliveryRead,
    p.deliveryUpdate,
    p.invoiceRead,
    p.invoiceCreate,
    p.invoiceUpdate,
    p.paymentRead,
    p.paymentRecord,
    p.statementRead,
    p.reportSalesRead,
    p.reportProductionRead,
    p.reportInventoryRead,
    p.reportFinancialRead,
    p.auditRead,
    p.documentRead,
    p.documentManage,
    p.aiIntakeRead,
    p.aiIntakeManage,
    p.notificationRead,
    p.requestRead,
    p.requestCreate,
    p.requestUpdate,
  ],

  SYSTEM_ADMINISTRATOR: [...PERMISSIONS],
};
