export {
  PERMISSIONS,
  ROLES,
  ROLE_PERMISSIONS,
  type Permission,
  type Role,
} from './catalog';
export { hasPermission } from './check';
export { can, canAny, canAll } from './access';
export {
  resolveAppSurface,
  resolveWebHomePath,
  resolveHomePersona,
  resolveMobileHomeHref,
  resolveComposedHomeKind,
  shouldFetchSalesAdminHome,
  WAREHOUSE_HOME_PERMISSIONS,
  type AppSurface,
  type HomePersona,
  type ComposedHomeKind,
} from './routing';
export {
  PERMISSION_GROUPS,
  PERMISSION_GROUP_LABELS,
  PERMISSION_META,
  expandPermissionDependencies,
  getPermissionMeta,
  groupedPermissionCatalog,
  isAssignableToStaff,
  type GroupedPermissionCatalog,
  type PermissionGroup,
  type PermissionMeta,
  type PermissionRiskLevel,
} from './permission-meta';
export {
  IDENTITY_ROLE_CODES,
  ROLE_KINDS,
  SYSTEM_STAFF_PRESETS,
  applyEmployeeTypeChange,
  applyIdentityChange,
  assertKnownPermissionCodes,
  employeeTypeFromKind,
  emptyUserIdentityForm,
  generateStaffTypeCode,
  hydrateUserIdentityForm,
  identityRoleCodeForKind,
  isIdentityRoleCode,
  isStaffRoleKind,
  roleKindFromIdentityCode,
  roleUsesDepartment,
  submittedRoleId,
  submittedStageDefinitionIds,
  type EmployeeType,
  type IdentityRoleCode,
  type RoleKind,
  type SystemStaffPresetCode,
  type UserIdentityForm,
} from './staff';
