import { PERMISSIONS, type Permission } from './catalog';

export const PERMISSION_GROUPS = [
  'inventory',
  'warehouses',
  'purchasing',
  'production',
  'quality',
  'delivery',
  'catalog',
  'customers',
  'sales',
  'users',
  'finance',
  'reports',
  'settings',
  'documents',
  'notifications',
  'scheduling',
  'ai',
] as const;

export type PermissionGroup = (typeof PERMISSION_GROUPS)[number];
export type PermissionRiskLevel = 'normal' | 'sensitive' | 'restricted';

export type PermissionMeta = {
  group: PermissionGroup;
  nameEn: string;
  nameAr: string;
  nameHe: string;
  descriptionEn: string;
  descriptionAr: string;
  descriptionHe: string;
  riskLevel: PermissionRiskLevel;
  assignableToStaff: boolean;
  requires?: Permission[];
};

export const PERMISSION_GROUP_LABELS: Record<
  PermissionGroup,
  { nameEn: string; nameAr: string; nameHe: string }
> = {
  inventory: { nameEn: 'Inventory', nameAr: 'المخزون', nameHe: 'מלאי' },
  warehouses: { nameEn: 'Warehouses', nameAr: 'المستودعات', nameHe: 'מחסנים' },
  purchasing: { nameEn: 'Purchasing', nameAr: 'المشتريات', nameHe: 'רכש' },
  production: { nameEn: 'Production', nameAr: 'الإنتاج', nameHe: 'ייצור' },
  quality: { nameEn: 'Quality', nameAr: 'الجودة', nameHe: 'איכות' },
  delivery: { nameEn: 'Delivery', nameAr: 'التوصيل', nameHe: 'משלוחים' },
  catalog: { nameEn: 'Catalog', nameAr: 'الكتالوج', nameHe: 'קטלוג' },
  customers: { nameEn: 'Dealers', nameAr: 'التجار', nameHe: 'סוחרים' },
  sales: { nameEn: 'Sales', nameAr: 'المبيعات', nameHe: 'מכירות' },
  users: { nameEn: 'Users', nameAr: 'المستخدمون', nameHe: 'משתמשים' },
  finance: { nameEn: 'Finance', nameAr: 'المالية', nameHe: 'כספים' },
  reports: { nameEn: 'Reports', nameAr: 'التقارير', nameHe: 'דוחות' },
  settings: { nameEn: 'Settings', nameAr: 'الإعدادات', nameHe: 'הגדרות' },
  documents: { nameEn: 'Documents', nameAr: 'المستندات', nameHe: 'מסמכים' },
  notifications: { nameEn: 'Notifications', nameAr: 'الإشعارات', nameHe: 'התראות' },
  scheduling: { nameEn: 'Scheduling', nameAr: 'الجدولة', nameHe: 'תזמון' },
  ai: { nameEn: 'AI', nameAr: 'الذكاء الاصطناعي', nameHe: 'בינה מלאכותית' },
};

function m(
  group: PermissionGroup,
  nameEn: string,
  nameAr: string,
  nameHe: string,
  descriptionEn: string,
  descriptionAr: string,
  descriptionHe: string,
  extra: Partial<Pick<PermissionMeta, 'riskLevel' | 'assignableToStaff' | 'requires'>> = {},
): PermissionMeta {
  return {
    group,
    nameEn,
    nameAr,
    nameHe,
    descriptionEn,
    descriptionAr,
    descriptionHe,
    riskLevel: extra.riskLevel ?? 'normal',
    assignableToStaff: extra.assignableToStaff ?? true,
    requires: extra.requires,
  };
}

const RESTRICTED = { riskLevel: 'restricted' as const, assignableToStaff: false };
const SENSITIVE = { riskLevel: 'sensitive' as const, assignableToStaff: true };

export const PERMISSION_META = {
  'customer.read': m(
    'customers',
    'View dealers',
    'عرض التجار',
    'צפייה בסוחרים',
    'See dealer profiles and contact details.',
    'عرض ملفات التجار وبيانات التواصل.',
    'צפייה בפרופילי סוחרים ופרטי קשר.',
  ),
  'customer.create': m(
    'customers',
    'Create dealers',
    'إضافة تجار',
    'יצירת סוחרים',
    'Add new dealer accounts.',
    'إضافة حسابات تجار جديدة.',
    'הוספת חשבונות סוחרים חדשים.',
    { requires: ['customer.read'] },
  ),
  'customer.update': m(
    'customers',
    'Update dealers',
    'تعديل التجار',
    'עדכון סוחרים',
    'Edit dealer information.',
    'تعديل بيانات التجار.',
    'עריכת פרטי סוחרים.',
    { requires: ['customer.read'] },
  ),
  'customer.delete': m(
    'customers',
    'Delete dealers',
    'حذف التجار',
    'מחיקת סוחרים',
    'Remove dealer accounts.',
    'حذف حسابات التجار.',
    'הסרת חשבונות סוחרים.',
    { ...SENSITIVE, requires: ['customer.read'] },
  ),
  'contact.manage': m(
    'customers',
    'Manage contacts',
    'إدارة جهات الاتصال',
    'ניהול אנשי קשר',
    'Add and edit dealer contacts.',
    'إضافة وتعديل جهات اتصال التجار.',
    'הוספה ועריכה של אנשי קשר.',
  ),
  'address.manage': m(
    'customers',
    'Manage addresses',
    'إدارة العناوين',
    'ניהול כתובות',
    'Add and edit dealer addresses.',
    'إضافة وتعديل عناوين التجار.',
    'הוספה ועריכה של כתובות.',
  ),
  'quotation.read': m(
    'sales',
    'View quotations',
    'عرض عروض الأسعار',
    'צפייה בהצעות מחיר',
    'See quotation documents.',
    'عرض مستندات عروض الأسعار.',
    'צפייה במסמכי הצעות מחיר.',
  ),
  'quotation.create': m(
    'sales',
    'Create quotations',
    'إنشاء عروض أسعار',
    'יצירת הצעות מחיר',
    'Draft new quotations.',
    'إعداد عروض أسعار جديدة.',
    'הכנת הצעות מחיר חדשות.',
    { requires: ['quotation.read'] },
  ),
  'quotation.update': m(
    'sales',
    'Update quotations',
    'تعديل عروض الأسعار',
    'עדכון הצעות מחיר',
    'Edit draft quotations.',
    'تعديل مسودات عروض الأسعار.',
    'עריכת טיוטות הצעות מחיר.',
    { requires: ['quotation.read'] },
  ),
  'quotation.submit': m(
    'sales',
    'Submit quotations',
    'إرسال عروض الأسعار للمراجعة',
    'הגשת הצעות מחיר',
    'Send quotations for internal review.',
    'إرسال عروض الأسعار للمراجعة الداخلية.',
    'שליחת הצעות מחיר לסקירה פנימית.',
    { requires: ['quotation.read'] },
  ),
  'quotation.approve': m(
    'sales',
    'Approve quotations',
    'اعتماد عروض الأسعار',
    'אישור הצעות מחיר',
    'Approve quotations for sending.',
    'اعتماد عروض الأسعار قبل الإرسال.',
    'אישור הצעות מחיר לפני שליחה.',
    { ...SENSITIVE, requires: ['quotation.read'] },
  ),
  'quotation.send': m(
    'sales',
    'Send quotations',
    'إرسال عروض الأسعار',
    'שליחת הצעות מחיר',
    'Send approved quotations to dealers.',
    'إرسال عروض الأسعار المعتمدة للتجار.',
    'שליחת הצעות מאושרות לסוחרים.',
    { requires: ['quotation.read'] },
  ),
  'quotation.accept': m(
    'sales',
    'Accept quotations',
    'قبول عروض الأسعار',
    'קבלת הצעות מחיר',
    'Accept a quotation as a dealer.',
    'قبول عرض السعر كتاجر.',
    'קבלת הצעת מחיר כסוחר.',
    { ...RESTRICTED, requires: ['quotation.read'] },
  ),
  'quotation.reject': m(
    'sales',
    'Reject quotations',
    'رفض عروض الأسعار',
    'דחיית הצעות מחיר',
    'Reject a quotation as a dealer.',
    'رفض عرض السعر كتاجر.',
    'דחיית הצעת מחיר כסוחר.',
  ),
  'quotation.revise': m(
    'sales',
    'Revise quotations',
    'تعديل عروض الأسعار بعد الإرسال',
    'תיקון הצעות מחיר',
    'Create a revised quotation.',
    'إنشاء نسخة معدّلة من عرض السعر.',
    'יצירת גרסה מתוקנת של הצעת מחיר.',
    { requires: ['quotation.read'] },
  ),
  'sales-order.read': m(
    'sales',
    'View sales orders',
    'عرض أوامر البيع',
    'צפייה בהזמנות מכירה',
    'See sales orders and progress.',
    'عرض أوامر البيع وتقدّمها.',
    'צפייה בהזמנות מכירה ובהתקדמותן.',
  ),
  'sales-order.create': m(
    'sales',
    'Create sales orders',
    'إنشاء أوامر بيع',
    'יצירת הזמנות מכירה',
    'Create sales orders from quotations.',
    'إنشاء أوامر بيع من عروض الأسعار.',
    'יצירת הזמנות מכירה מהצעות מחיר.',
    { requires: ['sales-order.read'] },
  ),
  'sales-order.update': m(
    'sales',
    'Update sales orders',
    'تعديل أوامر البيع',
    'עדכון הזמנות מכירה',
    'Edit sales order details.',
    'تعديل تفاصيل أوامر البيع.',
    'עריכת פרטי הזמנות מכירה.',
    { requires: ['sales-order.read'] },
  ),
  'contract.read': m(
    'sales',
    'View contracts',
    'عرض العقود',
    'צפייה בחוזים',
    'See sales contracts.',
    'عرض عقود البيع.',
    'צפייה בחוזי מכירה.',
  ),
  'contract.manage': m(
    'sales',
    'Manage contracts',
    'إدارة العقود',
    'ניהול חוזים',
    'Create and update contracts.',
    'إنشاء وتحديث العقود.',
    'יצירה ועדכון של חוזים.',
    { requires: ['contract.read'] },
  ),
  'supplier.read': m(
    'purchasing',
    'View suppliers',
    'عرض المورّدين',
    'צפייה בספקים',
    'See supplier records.',
    'عرض سجلات المورّدين.',
    'צפייה ברשומות ספקים.',
  ),
  'supplier.manage': m(
    'purchasing',
    'Manage suppliers',
    'إدارة المورّدين',
    'ניהול ספקים',
    'Create and update suppliers.',
    'إنشاء وتحديث المورّدين.',
    'יצירה ועדכון של ספקים.',
    { requires: ['supplier.read'] },
  ),
  'purchase-request.read': m(
    'purchasing',
    'View purchase requests',
    'عرض طلبات الشراء',
    'צפייה בבקשות רכש',
    'See purchase requests.',
    'عرض طلبات الشراء.',
    'צפייה בבקשות רכש.',
  ),
  'purchase-request.create': m(
    'purchasing',
    'Create purchase requests',
    'إنشاء طلبات شراء',
    'יצירת בקשות רכש',
    'Draft purchase requests.',
    'إعداد طلبات شراء.',
    'הכנת בקשות רכש.',
    { requires: ['purchase-request.read'] },
  ),
  'purchase-order.read': m(
    'purchasing',
    'View purchase orders',
    'عرض أوامر الشراء',
    'צפייה בהזמנות רכש',
    'See purchase orders.',
    'عرض أوامر الشراء.',
    'צפייה בהזמנות רכש.',
  ),
  'purchase-order.create': m(
    'purchasing',
    'Create purchase orders',
    'إنشاء أوامر شراء',
    'יצירת הזמנות רכש',
    'Create purchase orders.',
    'إنشاء أوامر شراء.',
    'יצירת הזמנות רכש.',
    { requires: ['purchase-order.read'] },
  ),
  'purchase-order.approve': m(
    'purchasing',
    'Approve purchase orders',
    'اعتماد أوامر الشراء',
    'אישור הזמנות רכש',
    'Approve purchase orders.',
    'اعتماد أوامر الشراء.',
    'אישור הזמנות רכש.',
    { ...SENSITIVE, requires: ['purchase-order.read'] },
  ),
  'supplier-invoice.read': m(
    'purchasing',
    'View supplier invoices',
    'عرض فواتير المورّدين',
    'צפייה בחשבוניות ספק',
    'See supplier invoices.',
    'عرض فواتير المورّدين.',
    'צפייה בחשבוניות ספק.',
  ),
  'supplier-invoice.create': m(
    'purchasing',
    'Create supplier invoices',
    'إنشاء فواتير مورّدين',
    'יצירת חשבוניות ספק',
    'Record supplier invoices.',
    'تسجيل فواتير المورّدين.',
    'רישום חשבוניות ספק.',
    { requires: ['supplier-invoice.read'] },
  ),
  'supplier-invoice.update': m(
    'purchasing',
    'Update supplier invoices',
    'تعديل فواتير المورّدين',
    'עדכון חשבוניות ספק',
    'Edit supplier invoice details.',
    'تعديل تفاصيل فواتير المورّدين.',
    'עריכת פרטי חשבוניות ספק.',
    { ...SENSITIVE, requires: ['supplier-invoice.read'] },
  ),
  'supplier-payment.record': m(
    'purchasing',
    'Record supplier payments',
    'تسجيل دفعات المورّدين',
    'רישום תשלומי ספק',
    'Record payments to suppliers.',
    'تسجيل الدفعات للمورّدين.',
    'רישום תשלומים לספקים.',
    { ...SENSITIVE, requires: ['supplier-invoice.read'] },
  ),
  'inventory.read': m(
    'inventory',
    'View inventory',
    'عرض المخزون',
    'צפייה במלאי',
    'See stock balances, lots, and history.',
    'عرض أرصدة المخزون والدفعات والسجل.',
    'צפייה ביתרות מלאי, אצוות והיסטוריה.',
  ),
  'inventory.receive': m(
    'inventory',
    'Receive stock',
    'استلام المخزون',
    'קליטת מלאי',
    'Receive materials into a warehouse.',
    'استلام المواد إلى المستودع.',
    'קליטת חומרים למחסן.',
    { requires: ['inventory.read'] },
  ),
  'inventory.issue': m(
    'inventory',
    'Issue stock',
    'صرف المخزون',
    'ניפוק מלאי',
    'Issue materials from a warehouse.',
    'صرف المواد من المستودع.',
    'ניפוק חומרים ממחסן.',
    { requires: ['inventory.read'] },
  ),
  'inventory.transfer': m(
    'inventory',
    'Transfer inventory',
    'نقل المخزون',
    'העברת מלאי',
    'Move inventory between compatible warehouses.',
    'نقل المخزون بين المستودعات المتوافقة.',
    'העברת מלאי בין מחסנים תואמים.',
    { requires: ['inventory.read', 'warehouse.read'] },
  ),
  'inventory.adjust': m(
    'inventory',
    'Adjust stock',
    'تعديل المخزون',
    'התאמת מלאי',
    'Create items and make quantity adjustments.',
    'إنشاء أصناف وتعديل الكميات.',
    'יצירת פריטים והתאמת כמויות.',
    { ...SENSITIVE, requires: ['inventory.read'] },
  ),
  'inventory.count': m(
    'inventory',
    'Stock count',
    'جرد المخزون',
    'ספירת מלאי',
    'Create and post stock counts.',
    'إنشاء وترحيل عمليات الجرد.',
    'יצירה ורישום של ספירות מלאי.',
    { requires: ['inventory.read'] },
  ),
  'inventory.cost.read': m(
    'inventory',
    'View inventory costs',
    'عرض تكاليف المخزون',
    'צפייה בעלויות מלאי',
    'See unit costs and inventory valuation.',
    'عرض تكلفة الوحدة وتقييم المخزون.',
    'צפייה בעלות יחידה ובהערכת מלאי.',
    { ...SENSITIVE, requires: ['inventory.read'] },
  ),
  'production-order.read': m(
    'production',
    'View production',
    'عرض الإنتاج',
    'צפייה בייצור',
    'See production orders and status.',
    'عرض أوامر الإنتاج وحالتها.',
    'צפייה בהזמנות ייצור ובסטטוס שלהן.',
  ),
  'production-order.create': m(
    'production',
    'Create production orders',
    'إنشاء أوامر إنتاج',
    'יצירת הזמנות ייצור',
    'Start new production orders.',
    'بدء أوامر إنتاج جديدة.',
    'פתיחת הזמנות ייצור חדשות.',
    { requires: ['production-order.read'] },
  ),
  'production-order.update': m(
    'production',
    'Update production orders',
    'تعديل أوامر الإنتاج',
    'עדכון הזמנות ייצור',
    'Edit production order details.',
    'تعديل تفاصيل أوامر الإنتاج.',
    'עריכת פרטי הזמנות ייצור.',
    { requires: ['production-order.read'] },
  ),
  'production-order.assign': m(
    'production',
    'Assign workers',
    'تعيين العمّال',
    'שיוך עובדים',
    'Assign production tasks to workers.',
    'تعيين مهام الإنتاج للعمّال.',
    'שיוך משימות ייצור לעובדים.',
    { requires: ['production-order.read'] },
  ),
  'production.setup.view': m(
    'production',
    'View production setup',
    'عرض إعداد الإنتاج',
    'צפייה בהכנת ייצור',
    'See order production setup before factory release.',
    'عرض إعداد الإنتاج للطلب قبل الإطلاق للمصنع.',
    'צפייה בהכנת הייצור להזמנה לפני שחרור לייצור.',
    { requires: ['sales-order.read'] },
  ),
  'production.setup.edit': m(
    'production',
    'Edit production setup',
    'تعديل إعداد الإنتاج',
    'עריכת הכנת ייצור',
    'Define materials, workflow, and packaging for an accepted order.',
    'تحديد المواد ومسار العمل والتعبئة لطلب مقبول.',
    'הגדרת חומרים, תהליך ואריזה להזמנה מאושרת.',
    { requires: ['production.setup.view'] },
  ),
  'production.setup.release': m(
    'production',
    'Release to production',
    'إطلاق للإنتاج',
    'שחרור לייצור',
    'Release a validated setup to create production orders.',
    'إطلاق إعداد مكتمل لإنشاء أوامر الإنتاج.',
    'שחרור הכנה מאומתת ליצירת הזמנות ייצור.',
    { ...SENSITIVE, requires: ['production.setup.view', 'production-order.create'] },
  ),
  'production.workflow.read': m(
    'production',
    'View workflows',
    'عرض سير الإنتاج',
    'צפייה בתהליכי ייצור',
    'See production workflow templates.',
    'عرض قوالب سير الإنتاج.',
    'צפייה בתבניות תהליך ייצור.',
  ),
  'production.workflow.manage': m(
    'production',
    'Manage workflow',
    'إدارة سير الإنتاج',
    'ניהול תהליך ייצור',
    'Edit production workflow templates.',
    'تعديل قوالب سير الإنتاج.',
    'עריכת תבניות תהליך ייצור.',
    { ...SENSITIVE, requires: ['production.workflow.read'] },
  ),
  'production.workflow.publish': m(
    'production',
    'Publish workflows',
    'نشر سير الإنتاج',
    'פרסום תהליכי ייצור',
    'Publish workflow versions for use.',
    'نشر إصدارات سير الإنتاج للاستخدام.',
    'פרסום גרסאות תהליך לשימוש.',
    { ...SENSITIVE, requires: ['production.workflow.read'] },
  ),
  'production.workflow.stage.manage': m(
    'production',
    'Manage stages',
    'إدارة مراحل الإنتاج',
    'ניהול שלבי ייצור',
    'Edit the production stage library.',
    'تعديل مكتبة مراحل الإنتاج.',
    'עריכת ספריית שלבי הייצור.',
    { ...SENSITIVE, requires: ['production.workflow.read'] },
  ),
  'production.workflow.order.customize': m(
    'production',
    'Customize order workflow',
    'تخصيص سير أمر الإنتاج',
    'התאמת תהליך להזמנה',
    'Override workflow on a production order.',
    'تعديل سير الإنتاج لأمر معيّن.',
    'עקיפת תהליך בהזמנת ייצור.',
    { requires: ['production-order.read'] },
  ),
  'production.workflow.order.read.own': m(
    'production',
    'View own order workflow',
    'عرض سير الطلب الخاص',
    'צפייה בתהליך ההזמנה שלי',
    'See workflow progress on own orders.',
    'عرض تقدّم سير الإنتاج للطلبات الخاصة.',
    'צפייה בהתקדמות התהליך בהזמנות שלי.',
  ),
  'production-task.read': m(
    'production',
    'View tasks',
    'عرض المهام',
    'צפייה במשימות',
    'See production tasks.',
    'عرض مهام الإنتاج.',
    'צפייה במשימות ייצור.',
  ),
  'production-task.update-own': m(
    'production',
    'Update own tasks',
    'تحديث المهام الخاصة',
    'עדכון המשימות שלי',
    'Start and update assigned tasks.',
    'بدء وتحديث المهام المعيّنة.',
    'התחלה ועדכון של משימות משויכות.',
    { requires: ['production-task.read'] },
  ),
  'production-task.update-any': m(
    'production',
    'Update any task',
    'تحديث أي مهمة',
    'עדכון כל משימה',
    'Update tasks assigned to anyone.',
    'تحديث المهام المعيّنة لأي عامل.',
    'עדכון משימות המשויכות לכל עובד.',
    { ...SENSITIVE, requires: ['production-task.read'] },
  ),
  'production-task.complete': m(
    'production',
    'Complete tasks',
    'إنهاء المهام',
    'השלמת משימות',
    'Mark production tasks complete.',
    'إنهاء مهام الإنتاج.',
    'סימון משימות ייצור כהושלמו.',
    { requires: ['production-task.read'] },
  ),
  'production.material-usage.record': m(
    'production',
    'Record material usage',
    'تسجيل استهلاك المواد',
    'רישום צריכת חומרים',
    'Confirm actual materials used on an assigned production task (not general warehouse issue).',
    'تأكيد المواد المستخدمة فعلياً على مهمة إنتاج معيّنة (وليس صرف مخزون عام).',
    'אישור חומרים בפועל במשימת ייצור משויכת (לא ניפוק מחסן כללי).',
    { requires: ['production-task.read'] },
  ),
  'quality-inspection.read': m(
    'quality',
    'View inspections',
    'عرض الفحوصات',
    'צפייה בבדיקות',
    'See quality inspections.',
    'عرض فحوصات الجودة.',
    'צפייה בבדיקות איכות.',
  ),
  'quality-inspection.perform': m(
    'quality',
    'Perform inspections',
    'تنفيذ الفحوصات',
    'ביצוע בדיקות',
    'Fill and submit inspections.',
    'تعبئة وتقديم فحوصات الجودة.',
    'מילוי והגשת בדיקות איכות.',
    { requires: ['quality-inspection.read'] },
  ),
  'quality-inspection.approve': m(
    'quality',
    'Approve inspections',
    'اعتماد الفحوصات',
    'אישור בדיקות',
    'Approve or reject inspection results.',
    'اعتماد أو رفض نتائج الفحص.',
    'אישור או דחייה של תוצאות בדיקה.',
    { requires: ['quality-inspection.read'] },
  ),
  'delivery.read': m(
    'delivery',
    'View deliveries',
    'عرض التوصيل',
    'צפייה במשלוחים',
    'See delivery jobs and status.',
    'عرض مهام التوصيل وحالتها.',
    'צפייה במשימות משלוח ובסטטוס.',
  ),
  'delivery.update': m(
    'delivery',
    'Update deliveries',
    'تحديث التوصيل',
    'עדכון משלוחים',
    'Plan and ship deliveries (not dealer receipt).',
    'تخطيط وشحن التوصيل (ليس تأكيد الاستلام).',
    'תכנון ומשלוח (לא אישור קבלה של הסוכן).',
    { requires: ['delivery.read'] },
  ),
  'delivery.confirm-own-receipt': m(
    'delivery',
    'Confirm own delivery receipt',
    'تأكيد استلام التوصيل',
    'אישור קבלת משלוח',
    'Dealer confirms physical receipt of an out-for-delivery shipment.',
    'يؤكد الموزع الاستلام الفعلي للشحنة الخارجة للتسليم.',
    'הסוכן מאשר קבלה פיזית של משלוח בדרך.',
    { requires: ['delivery.read'] },
  ),
  'invoice.read': m(
    'finance',
    'View invoices',
    'عرض الفواتير',
    'צפייה בחשבוניות',
    'See customer invoices.',
    'عرض فواتير العملاء.',
    'צפייה בחשבוניות לקוח.',
  ),
  'invoice.create': m(
    'finance',
    'Create invoices',
    'إنشاء الفواتير',
    'יצירת חשבוניות',
    'Issue customer invoices.',
    'إصدار فواتير للعملاء.',
    'הפקת חשבוניות ללקוחות.',
    { ...SENSITIVE, requires: ['invoice.read'] },
  ),
  'invoice.update': m(
    'finance',
    'Update invoices',
    'تعديل الفواتير',
    'עדכון חשבוניות',
    'Edit invoice details.',
    'تعديل تفاصيل الفواتير.',
    'עריכת פרטי חשבוניות.',
    { ...SENSITIVE, requires: ['invoice.read'] },
  ),
  'payment.read': m(
    'finance',
    'View payments',
    'عرض الدفعات',
    'צפייה בתשלומים',
    'See recorded payments.',
    'عرض الدفعات المسجّلة.',
    'צפייה בתשלומים שנרשמו.',
  ),
  'payment.record': m(
    'finance',
    'Record payments',
    'تسجيل الدفعات',
    'רישום תשלומים',
    'Record customer payments.',
    'تسجيل دفعات العملاء.',
    'רישום תשלומי לקוחות.',
    { ...SENSITIVE, requires: ['payment.read'] },
  ),
  'statement.read': m(
    'finance',
    'View statements',
    'عرض كشوف الحساب',
    'צפייה בדוחות חשבון',
    'See dealer account statements.',
    'عرض كشوف حساب التجار.',
    'צפייה בדוחות חשבון של סוחרים.',
  ),
  'report.sales.read': m(
    'reports',
    'Sales reports',
    'تقارير المبيعات',
    'דוחות מכירות',
    'See sales dashboards and reports.',
    'عرض لوحات وتقارير المبيعات.',
    'צפייה בלוחות מחוונים ודוחות מכירות.',
  ),
  'report.production.read': m(
    'reports',
    'Production reports',
    'تقارير الإنتاج',
    'דוחות ייצור',
    'See production dashboards and reports.',
    'عرض لوحات وتقارير الإنتاج.',
    'צפייה בלוחות מחוונים ודוחות ייצור.',
  ),
  'report.inventory.read': m(
    'reports',
    'Inventory reports',
    'تقارير المخزون',
    'דוחות מלאי',
    'See inventory reports.',
    'عرض تقارير المخزون.',
    'צפייה בדוחות מלאי.',
    { requires: ['inventory.read'] },
  ),
  'report.financial.read': m(
    'reports',
    'Financial reports',
    'التقارير المالية',
    'דוחות כספיים',
    'See financial and profit reports.',
    'عرض التقارير المالية والأرباح.',
    'צפייה בדוחות כספיים ורווחיות.',
    SENSITIVE,
  ),
  'user.manage': m(
    'users',
    'Manage users',
    'إدارة المستخدمين',
    'ניהול משתמשים',
    'Create and edit login accounts.',
    'إنشاء وتعديل حسابات الدخول.',
    'יצירה ועריכה של חשבונות כניסה.',
    SENSITIVE,
  ),
  'role.manage': m(
    'users',
    'Manage staff types',
    'إدارة أنواع الموظفين',
    'ניהול סוגי משרות',
    'Create staff types and assign permissions.',
    'إنشاء أنواع الموظفين وتحديد الصلاحيات.',
    'יצירת סוגי משרות והקצאת הרשאות.',
    RESTRICTED,
  ),
  'settings.manage': m(
    'settings',
    'Manage settings',
    'إدارة الإعدادات',
    'ניהול הגדרות',
    'Change company and system settings.',
    'تعديل إعدادات الشركة والنظام.',
    'שינוי הגדרות חברה ומערכת.',
    RESTRICTED,
  ),
  'catalog.manage': m(
    'catalog',
    'Manage catalog',
    'إدارة الكتالوج',
    'ניהול קטלוג',
    'Edit products, materials, and production setup.',
    'تعديل المنتجات والمواد وإعداد الإنتاج.',
    'עריכת מוצרים, חומרים והגדרת ייצור.',
    SENSITIVE,
  ),
  'catalog.read': m(
    'catalog',
    'View catalog',
    'عرض الكتالوج',
    'צפייה בקטלוג',
    'See products and materials.',
    'عرض المنتجات والمواد.',
    'צפייה במוצרים ובחומרים.',
  ),
  'department.manage': m(
    'users',
    'Manage departments',
    'إدارة الأقسام',
    'ניהול מחלקות',
    'Create and edit departments.',
    'إنشاء وتعديل الأقسام.',
    'יצירה ועריכה של מחלקות.',
    SENSITIVE,
  ),
  'warehouse.read': m(
    'warehouses',
    'View warehouses',
    'عرض المستودعات',
    'צפייה במחסנים',
    'See warehouses used for stock operations.',
    'عرض المستودعات المستخدمة لعمليات المخزون.',
    'צפייה במחסנים לפעולות מלאי.',
  ),
  'warehouse.manage': m(
    'warehouses',
    'Manage warehouses',
    'إدارة المستودعات',
    'ניהול מחסנים',
    'Create and configure warehouses.',
    'إنشاء وضبط المستودعات.',
    'יצירה והגדרה של מחסנים.',
    { ...SENSITIVE, requires: ['warehouse.read'] },
  ),
  'audit.read': m(
    'settings',
    'View audit log',
    'عرض سجل التدقيق',
    'צפייה ביומן ביקורת',
    'See security and change history.',
    'عرض سجل الأمان والتغييرات.',
    'צפייה בהיסטוריית אבטחה ושינויים.',
    RESTRICTED,
  ),
  'document.read': m(
    'documents',
    'View documents',
    'عرض المستندات',
    'צפייה במסמכים',
    'Open attached documents and labels.',
    'فتح المستندات والملصقات المرفقة.',
    'פתיחת מסמכים ותוויות מצורפים.',
  ),
  'document.manage': m(
    'documents',
    'Manage documents',
    'إدارة المستندات',
    'ניהול מסמכים',
    'Upload and organize documents.',
    'رفع وتنظيم المستندات.',
    'העלאה וארגון של מסמכים.',
    { requires: ['document.read'] },
  ),
  'ai-intake.read': m(
    'ai',
    'View AI intake',
    'عرض استقبال الذكاء الاصطناعي',
    'צפייה בקליטת בינה מלאכותית',
    'See AI-captured requests.',
    'عرض الطلبات المستلمة بالذكاء الاصطناعي.',
    'צפייה בבקשות שנקלטו בבינה מלאכותית.',
  ),
  'ai-intake.manage': m(
    'ai',
    'Manage AI intake',
    'إدارة استقبال الذكاء الاصطناعي',
    'ניהול קליטת בינה מלאכותית',
    'Process AI-captured requests.',
    'معالجة الطلبات المستلمة بالذكاء الاصطناعي.',
    'טיפול בבקשות שנקלטו בבינה מלאכותית.',
    { requires: ['ai-intake.read'] },
  ),
  'ai-chat.read': m(
    'ai',
    'Use AI chat',
    'استخدام محادثة الذكاء الاصطناعي',
    'שימוש בצ׳אט בינה מלאכותית',
    'Open the factory AI assistant.',
    'فتح مساعد المصنع الذكي.',
    'פתיחת עוזר הבינה המלאכותית של המפעל.',
  ),
  'notification.read': m(
    'notifications',
    'View notifications',
    'عرض الإشعارات',
    'צפייה בהתראות',
    'See in-app notifications.',
    'عرض الإشعارات داخل التطبيق.',
    'צפייה בהתראות באפליקציה.',
  ),
  'request.read': m(
    'sales',
    'View price requests',
    'عرض طلبات التسعير',
    'צפייה בבקשות מחיר',
    'See dealer price requests.',
    'عرض طلبات التسعير من التجار.',
    'צפייה בבקשות מחיר מסוחרים.',
  ),
  'request.create': m(
    'sales',
    'Create price requests',
    'إنشاء طلبات تسعير',
    'יצירת בקשות מחיר',
    'Submit a new price request.',
    'تقديم طلب تسعير جديد.',
    'שליחת בקשת מחיר חדשה.',
    { requires: ['request.read'] },
  ),
  'request.update': m(
    'sales',
    'Update price requests',
    'تعديل طلبات التسعير',
    'עדכון בקשות מחיר',
    'Edit price requests.',
    'تعديل طلبات التسعير.',
    'עריכת בקשות מחיר.',
    { requires: ['request.read'] },
  ),
  'schedule.read': m(
    'scheduling',
    'View schedule',
    'عرض الجدول',
    'צפייה בלוח זמנים',
    'See the factory schedule.',
    'عرض جدول المصنع.',
    'צפייה בלוח הזמנים של המפעל.',
  ),
  'schedule.manage': m(
    'scheduling',
    'Manage schedule',
    'إدارة الجدول',
    'ניהול לוח זמנים',
    'Create and edit schedule allocations.',
    'إنشاء وتعديل تخصيصات الجدول.',
    'יצירה ועריכה של הקצאות בלוח הזמנים.',
    { requires: ['schedule.read'] },
  ),
  'schedule.approve': m(
    'scheduling',
    'Approve schedule',
    'اعتماد الجدول',
    'אישור לוח זמנים',
    'Approve production schedules.',
    'اعتماد جداول الإنتاج.',
    'אישור לוחות זמנים לייצור.',
    { ...SENSITIVE, requires: ['schedule.read'] },
  ),
  'schedule.override': m(
    'scheduling',
    'Override schedule',
    'تجاوز الجدول',
    'עקיפת לוח זמנים',
    'Override schedule constraints.',
    'تجاوز قيود الجدول.',
    'עקיפת מגבלות לוח הזמנים.',
    { ...SENSITIVE, requires: ['schedule.read'] },
  ),
  'schedule.settings.manage': m(
    'scheduling',
    'Manage schedule settings',
    'إدارة إعدادات الجدول',
    'ניהול הגדרות לוח זמנים',
    'Change factory calendar and capacity settings.',
    'تعديل تقويم المصنع وإعدادات الطاقة.',
    'שינוי לוח שנה והגדרות קיבולת של המפעל.',
    SENSITIVE,
  ),
  'schedule.capacity.read': m(
    'scheduling',
    'View capacity',
    'عرض الطاقة الإنتاجية',
    'צפייה בקיבולת',
    'See capacity and load.',
    'عرض الطاقة الإنتاجية والضغط.',
    'צפייה בקיבולת ובעומס.',
  ),
  'schedule.availability.own': m(
    'scheduling',
    'View own availability',
    'عرض التوفر الخاص',
    'צפייה בזמינות שלי',
    'See own scheduling availability.',
    'عرض التوفر الخاص في الجدول.',
    'צפייה בזמינות האישית בלוח הזמנים.',
  ),
  'schedule.read.own': m(
    'scheduling',
    'View own schedule',
    'عرض الجدول الخاص',
    'צפייה בלוח הזמנים שלי',
    'See own scheduled work.',
    'عرض العمل المجدول الخاص.',
    'צפייה בעבודה המתוזמנת שלי.',
  ),
  'schedule.request-change.own': m(
    'scheduling',
    'Request schedule change',
    'طلب تعديل الجدول',
    'בקשת שינוי בלוח זמנים',
    'Request a change to own schedule.',
    'طلب تعديل الجدول الخاص.',
    'בקשת שינוי בלוח הזמנים האישי.',
  ),
} as const satisfies Record<Permission, PermissionMeta>;

export function getPermissionMeta(code: Permission): PermissionMeta {
  return PERMISSION_META[code];
}

export function isAssignableToStaff(code: Permission): boolean {
  return PERMISSION_META[code].assignableToStaff;
}

/** Expand implied permissions so saved staff types are usable. */
export function expandPermissionDependencies(codes: readonly string[]): Permission[] {
  const known = new Set<Permission>(PERMISSIONS);
  const selected = new Set<Permission>();
  for (const code of codes) {
    if (known.has(code as Permission)) selected.add(code as Permission);
  }

  let changed = true;
  while (changed) {
    changed = false;
    for (const code of [...selected]) {
      for (const required of PERMISSION_META[code].requires ?? []) {
        if (!selected.has(required)) {
          selected.add(required);
          changed = true;
        }
      }
    }
  }

  return PERMISSIONS.filter((code) => selected.has(code));
}

export type GroupedPermissionCatalog = Array<{
  group: PermissionGroup;
  nameEn: string;
  nameAr: string;
  nameHe: string;
  permissions: Array<PermissionMeta & { code: Permission }>;
}>;

export function groupedPermissionCatalog(opts?: {
  assignableToStaffOnly?: boolean;
}): GroupedPermissionCatalog {
  const byGroup = new Map<PermissionGroup, Array<PermissionMeta & { code: Permission }>>();
  for (const code of PERMISSIONS) {
    const meta = PERMISSION_META[code];
    if (opts?.assignableToStaffOnly && !meta.assignableToStaff) continue;
    const list = byGroup.get(meta.group) ?? [];
    list.push({ code, ...meta });
    byGroup.set(meta.group, list);
  }

  return PERMISSION_GROUPS.filter((group) => byGroup.has(group)).map((group) => ({
    group,
    ...PERMISSION_GROUP_LABELS[group],
    permissions: byGroup.get(group) ?? [],
  }));
}
