import type { BrowseCategory, BrowseProduct } from './api';

export const catalogCategoriesFixture: BrowseCategory[] = [
  { id: 'cat1', code: 'SOFA', nameEn: 'Sofas', nameAr: 'كنب', nameHe: 'ספות' },
  { id: 'cat2', code: 'TABLE', nameEn: 'Tables', nameAr: 'طاولات', nameHe: 'שולחנות' },
  { id: 'cat3', code: 'CHAIR', nameEn: 'Chairs', nameAr: 'كراسي', nameHe: 'כיסאות' },
];

export const catalogProductsFixture: BrowseProduct[] = [
  {
    id: 'p1',
    sku: 'SF-001',
    nameEn: 'Modern Sofa',
    nameAr: 'كنبة عصرية',
    description: 'Comfortable 3-seater premium sofa with high quality fabric.',
    imageUrl: null,
    galleryUrls: [],
    isActive: true,
    price: 850,
    dealerPrice: 850,
    priceCurrency: 'ILS',
    width: 220,
    height: 85,
    depth: 90,
    seatHeight: 45,
    unit: 'pcs',
    categoryId: 'cat1',
    category: catalogCategoriesFixture[0]!,
  },
  {
    id: 'p2',
    sku: 'TB-010',
    nameEn: 'Dining Table',
    nameAr: 'طاولة طعام',
    description: 'Solid wood dining table for eight.',
    imageUrl: null,
    isActive: true,
    price: 1200,
    dealerPrice: 1200,
    priceCurrency: 'ILS',
    width: 180,
    height: 75,
    depth: 90,
    unit: 'pcs',
    categoryId: 'cat2',
    category: catalogCategoriesFixture[1]!,
  },
  {
    id: 'p3',
    sku: 'CH-003',
    nameEn: 'Lounge Chair',
    nameAr: 'كرسي استرخاء',
    imageUrl: null,
    isActive: true,
    price: 420,
    dealerPrice: 420,
    priceCurrency: 'ILS',
    width: 78,
    height: 92,
    depth: 82,
    seatHeight: 45,
    unit: 'pcs',
    categoryId: 'cat3',
    category: catalogCategoriesFixture[2]!,
  },
  {
    id: 'p4',
    sku: 'SF-002',
    nameEn: 'Corner Sofa',
    nameAr: 'كنبة زاوية',
    imageUrl: null,
    isActive: true,
    price: 1450,
    dealerPrice: 1450,
    priceCurrency: 'ILS',
    width: 280,
    height: 85,
    depth: 100,
    seatHeight: 45,
    unit: 'pcs',
    categoryId: 'cat1',
    category: catalogCategoriesFixture[0]!,
  },
];
