import type { PrismaClient } from '@prisma/client';

/**
 * Wipe operational data so the 8-month world can be re-seeded.
 * Preserves IAM foundation, warehouses, departments, stage defs, QC templates,
 * notification templates, and system_settings.
 */
export async function wipeOperationalData(prisma: PrismaClient): Promise<void> {
  const tables = [
    'ai_extraction_fields',
    'ai_extraction_jobs',
    'audit_events',
    'idempotency_records',
    'device_push_tokens',
    'communication_logs',
    'notifications',
    'documents',
    'return_requests',
    'supplier_payments',
    'supplier_invoice_lines',
    'supplier_invoices',
    'statement_entries',
    'payments',
    'invoice_lines',
    'invoices',
    'delivery_items',
    'deliveries',
    'quality_defects',
    'quality_inspection_items',
    'rework_requests',
    'quality_inspections',
    'task_blockers',
    'task_time_entries',
    'schedule_allocations',
    'production_schedules',
    'scheduling_estimate_proposals',
    'product_stage_estimates',
    'product_production_profiles',
    'production_order_workflow_snapshot_edges',
    'production_order_workflow_snapshot_nodes',
    'production_order_workflow_snapshots',
    'production_tasks',
    'production_stage_instances',
    'production_orders',
    'contracts',
    'sales_order_lines',
    'sales_orders',
    'quotation_approvals',
    'quotation_lines',
    'quotations',
    'request_items',
    'requests_for_quotation',
    'warehouse_transfer_lines',
    'warehouse_transfers',
    'inventory_count_lines',
    'inventory_counts',
    'inventory_transactions',
    'inventory_balances',
    'goods_receipt_lines',
    'goods_receipts',
    'purchase_order_lines',
    'purchase_orders',
    'supplier_quote_offers',
    'purchase_request_lines',
    'purchase_requests',
    'inventory_items',
    'warehouse_locations',
    'dealer_prices',
    'products',
    'product_categories',
    'materials',
    'fabrics',
    'color_references',
    'supplier_contacts',
    'suppliers',
    'customer_addresses',
    'customer_contacts',
    'customers',
    'sessions',
    'user_roles',
    'users',
    'sequence_counters',
  ];

  await prisma.$executeRawUnsafe(
    `TRUNCATE TABLE ${tables.map((t) => `"${t}"`).join(', ')} RESTART IDENTITY CASCADE`,
  );
}
