/** Presentation-quality names for generated extra sales orders. Indexed by extra `n`. */
export const EXTRA_PROJECT_NAMES = [
  'Jabal Amman Dining Room',
  'Oasis Living Window Seat',
  'Balqis Hotel Corridor Benches',
  'Cedar Villa Majlis',
  'Zaatar Home Entry Ottoman',
  'Qasr Hotel Lobby Seating',
  'Rawnaq Residence Bedroom Set',
  'Diwan Club Reading Chairs',
  'Noor Boutique Window Set',
  'Nile Interiors Showroom Refresh',
  'Sweifieh Family Lounge',
  'Abdali Tower Reception',
  'Dabouq Guest Suite',
  'Khalda Apartment Dining',
  'Shmeisani Office Lounge',
  'Rainbow Street Cafe Banquette',
  'Four Seasons Banquet Overflow',
  'Tlaa Al Ali Living Room',
  'Jubeiha Clinic Waiting Area',
  'Mecca Street Boutique',
  'City Mall Pop-up',
  'University Street Studio',
  'Gardens Street Townhouse',
  'Sweifieh Penthouse Study',
  'Abdoun Duplex Landing',
  'Dabouq Majlis Refresh',
  'Airport Road Villa Dining',
  'Al Weibdeh Artist Loft',
  'Jabal Al Weibdeh Cafe',
  'King Abdullah Design Center',
  'Amman Marriott Overflow',
  'Hilton Dead Sea Cabana',
  'Aqaba Resort Lounge',
  'Irbid Showroom Floor',
  'Zarqa Family Dining',
  'Salt Old Town Sitting Room',
  'Madaba Guest House',
  'Fuheis Cottage',
  'Naur Farmhouse',
  'Marj Al Hamam Residence',
  'Khalda Kids Play Room',
  'Abdoun Clinic Consultation',
  'Shmeisani Law Office',
  'Rainbow Street Bookshop',
  'Qasr Ballroom Side Tables',
  'Rawnaq Window Display',
  'Diwan Boardroom Chairs',
  'Noor Bridal Suite',
  'Cedar Lake House',
  'Zaatar Terrace Seating',
  'Oasis Spa Relaxation',
  'Balqis Wedding Majlis',
  'Nile Interiors Autumn Floor',
] as const;
