export type ParityStatus = 'ported' | 'intentionally-native-only' | 'deferred';

export type ParityRow = {
  mobile: string;
  web: string | null;
  surface: 'auth' | 'admin' | 'dealer' | 'worker' | 'shared' | 'dev';
  status: ParityStatus;
};

export const WEB_PARITY: ParityRow[] = [
  { mobile: '/(app)/(admin)/(tabs)', web: '/admin/dashboard', surface: 'admin', status: 'ported' },
  { mobile: '/(app)/(admin)/(tabs)/inventory', web: '/admin/inventory', surface: 'admin', status: 'ported' },
  { mobile: '/(app)/(admin)/(tabs)/more', web: '/admin/more/account', surface: 'admin', status: 'ported' },
  { mobile: '/(app)/(admin)/(tabs)/orders', web: '/admin/orders', surface: 'admin', status: 'ported' },
  { mobile: '/(app)/(admin)/(tabs)/production', web: '/admin/production', surface: 'admin', status: 'ported' },
  { mobile: '/(app)/(admin)/ai-chat', web: '/admin/ai-chat', surface: 'admin', status: 'ported' },
  { mobile: '/(app)/(admin)/ai-intake/[id]', web: '/admin/ai-intake/[id]', surface: 'admin', status: 'ported' },
  { mobile: '/(app)/(admin)/ai-intake', web: '/admin/ai-intake', surface: 'admin', status: 'ported' },
  { mobile: '/(app)/(admin)/dealers/[id]', web: '/admin/customers/[id]', surface: 'admin', status: 'ported' },
  { mobile: '/(app)/(admin)/dealers', web: '/admin/customers', surface: 'admin', status: 'ported' },
  { mobile: '/(app)/(admin)/deliveries/[id]', web: '/admin/deliveries/[id]', surface: 'admin', status: 'ported' },
  { mobile: '/(app)/(admin)/inventory/[group]', web: '/admin/inventory/[group]', surface: 'admin', status: 'ported' },
  { mobile: '/(app)/(admin)/inventory/fabric-bundle/[code]', web: '/admin/inventory/fabric-bundle/[code]', surface: 'admin', status: 'ported' },
  { mobile: '/(app)/(admin)/inventory/finished/[salesOrderId]', web: '/admin/inventory/finished/[salesOrderId]', surface: 'admin', status: 'ported' },
  { mobile: '/(app)/(admin)/inventory/items/[id]', web: '/admin/inventory/items/[id]', surface: 'admin', status: 'ported' },
  { mobile: '/(app)/(admin)/inventory/low-stock', web: '/admin/inventory/low-stock', surface: 'admin', status: 'ported' },
  { mobile: '/(app)/(admin)/inventory/receive/[id]', web: '/admin/inventory/receive/[id]', surface: 'admin', status: 'ported' },
  { mobile: '/(app)/(admin)/inventory/receive', web: '/admin/inventory/receive', surface: 'admin', status: 'ported' },
  { mobile: '/(app)/(admin)/inventory/semi/[orderId]', web: '/admin/inventory/semi/[orderId]', surface: 'admin', status: 'ported' },
  { mobile: '/(app)/(admin)/inventory/warehouses/[id]', web: '/admin/inventory/warehouses/[id]', surface: 'admin', status: 'ported' },
  { mobile: '/(app)/(admin)/inventory/warehouses', web: '/admin/inventory/warehouses', surface: 'admin', status: 'ported' },
  { mobile: '/(app)/(admin)/invoices/[id]', web: '/admin/invoices/[id]', surface: 'admin', status: 'ported' },
  { mobile: '/(app)/(admin)/invoices', web: '/admin/invoices', surface: 'admin', status: 'ported' },
  { mobile: '/(app)/(admin)/more/account', web: '/admin/more/account', surface: 'admin', status: 'ported' },
  { mobile: '/(app)/(admin)/more/notifications', web: '/admin/more/notifications', surface: 'admin', status: 'ported' },
  { mobile: '/(app)/(admin)/more/settings', web: '/admin/more/settings', surface: 'admin', status: 'ported' },
  { mobile: '/(app)/(admin)/orders/[id]/flow', web: '/admin/orders/[id]/flow', surface: 'admin', status: 'ported' },
  { mobile: '/(app)/(admin)/orders/[id]', web: '/admin/orders/[id]', surface: 'admin', status: 'ported' },
  { mobile: '/(app)/(admin)/orders/[id]/production-plan', web: '/admin/orders/[id]/production-plan', surface: 'admin', status: 'ported' },
  { mobile: '/(app)/(admin)/orders/[id]/production-setup', web: '/admin/orders/[id]/production-setup', surface: 'admin', status: 'ported' },
  { mobile: '/(app)/(admin)/orders/[id]/production-setup/lines/[lineId]', web: '/admin/orders/[id]/production-setup/lines/[lineId]', surface: 'admin', status: 'ported' },
  { mobile: '/(app)/(admin)/production/[id]/flow', web: '/admin/production/[id]/flow', surface: 'admin', status: 'ported' },
  { mobile: '/(app)/(admin)/production/[id]', web: '/admin/production/[id]', surface: 'admin', status: 'ported' },
  { mobile: '/(app)/(admin)/production/[id]/plan', web: '/admin/production/[id]/plan', surface: 'admin', status: 'ported' },
  { mobile: '/(app)/(admin)/production/[id]/setup', web: '/admin/production/[id]/setup', surface: 'admin', status: 'ported' },
  { mobile: '/(app)/(admin)/production/problems', web: '/admin/production/problems', surface: 'admin', status: 'ported' },
  { mobile: '/(app)/(admin)/production/tasks/[id]', web: '/admin/production/tasks/[id]', surface: 'admin', status: 'ported' },
  { mobile: '/(app)/(admin)/production/workflow/[id]', web: '/admin/production/workflow/[id]', surface: 'admin', status: 'ported' },
  { mobile: '/(app)/(admin)/production/workflow', web: '/admin/production/workflow', surface: 'admin', status: 'ported' },
  { mobile: '/(app)/(admin)/production/workflow/stages', web: '/admin/production/workflow/stages', surface: 'admin', status: 'ported' },
  { mobile: '/(app)/(admin)/products/[id]', web: '/admin/products/[id]', surface: 'admin', status: 'ported' },
  { mobile: '/(app)/(admin)/products/[id]/production-setup', web: '/admin/products/[id]/production-setup', surface: 'admin', status: 'ported' },
  { mobile: '/(app)/(admin)/products/[id]/variants/[variantId]', web: '/admin/products/[id]/variants/[variantId]', surface: 'admin', status: 'ported' },
  { mobile: '/(app)/(admin)/products', web: '/admin/products', surface: 'admin', status: 'ported' },
  { mobile: '/(app)/(admin)/purchasing/[id]', web: '/admin/purchasing/[id]', surface: 'admin', status: 'ported' },
  { mobile: '/(app)/(admin)/purchasing/create', web: '/admin/purchasing/create', surface: 'admin', status: 'ported' },
  { mobile: '/(app)/(admin)/purchasing/fabric/[id]', web: '/admin/purchasing/fabric/[id]', surface: 'admin', status: 'ported' },
  { mobile: '/(app)/(admin)/purchasing', web: '/admin/purchasing', surface: 'admin', status: 'ported' },
  { mobile: '/(app)/(admin)/purchasing/low-stock', web: '/admin/purchasing/low-stock', surface: 'admin', status: 'ported' },
  { mobile: '/(app)/(admin)/purchasing/new', web: '/admin/purchasing/new', surface: 'admin', status: 'ported' },
  { mobile: '/(app)/(admin)/purchasing/runs/[id]', web: '/admin/purchasing/runs/[id]', surface: 'admin', status: 'ported' },
  { mobile: '/(app)/(admin)/purchasing/supplier-invoices/[id]', web: '/admin/purchasing/supplier-invoices/[id]', surface: 'admin', status: 'ported' },
  { mobile: '/(app)/(admin)/purchasing/suppliers/[id]', web: '/admin/purchasing/suppliers/[id]', surface: 'admin', status: 'ported' },
  { mobile: '/(app)/(admin)/purchasing/suppliers/[id]/orders', web: '/admin/purchasing/suppliers/[id]/orders', surface: 'admin', status: 'ported' },
  { mobile: '/(app)/(admin)/purchasing/suppliers', web: '/admin/purchasing/suppliers', surface: 'admin', status: 'ported' },
  { mobile: '/(app)/(admin)/quotations/[id]/lines/[lineId]', web: '/admin/quotations/[id]/lines/[lineId]', surface: 'admin', status: 'ported' },
  { mobile: '/(app)/(admin)/quotations/[id]', web: '/admin/quotations/[id]', surface: 'admin', status: 'ported' },
  { mobile: '/(app)/(admin)/reports/coverage/[issueType]', web: '/admin/reports/coverage/[issueType]', surface: 'admin', status: 'ported' },
  { mobile: '/(app)/(admin)/reports/coverage/[type]', web: '/admin/reports/coverage/[type]', surface: 'admin', status: 'ported' },
  { mobile: '/(app)/(admin)/reports/coverage', web: '/admin/reports/coverage', surface: 'admin', status: 'ported' },
  { mobile: '/(app)/(admin)/reports', web: '/admin/reports', surface: 'admin', status: 'ported' },
  { mobile: '/(app)/(admin)/reports/inventory/[itemId]', web: '/admin/reports/inventory/[itemId]', surface: 'admin', status: 'ported' },
  { mobile: '/(app)/(admin)/reports/inventory', web: '/admin/reports/inventory', surface: 'admin', status: 'ported' },
  { mobile: '/(app)/(admin)/reports/order/[id]', web: '/admin/reports/order/[id]', surface: 'admin', status: 'ported' },
  { mobile: '/(app)/(admin)/reports/orders', web: '/admin/reports/orders', surface: 'admin', status: 'ported' },
  { mobile: '/(app)/(admin)/reports/products/[productId]/variants/[variantId]', web: '/admin/reports/products/[productId]/variants/[variantId]', surface: 'admin', status: 'ported' },
  { mobile: '/(app)/(admin)/reports/products/[productId]', web: '/admin/reports/products/[productId]', surface: 'admin', status: 'ported' },
  { mobile: '/(app)/(admin)/reports/products/custom', web: '/admin/reports/products/custom', surface: 'admin', status: 'ported' },
  { mobile: '/(app)/(admin)/reports/products', web: '/admin/reports/products', surface: 'admin', status: 'ported' },
  { mobile: '/(app)/(admin)/reports/returns/[id]', web: '/admin/reports/returns/[id]', surface: 'admin', status: 'ported' },
  { mobile: '/(app)/(admin)/reports/returns', web: '/admin/reports/returns', surface: 'admin', status: 'ported' },
  { mobile: '/(app)/(admin)/requests/[id]/lines/[itemId]', web: '/admin/requests/[id]/lines/[itemId]', surface: 'admin', status: 'ported' },
  { mobile: '/(app)/(admin)/requests/[id]', web: '/admin/requests/[id]', surface: 'admin', status: 'ported' },
  { mobile: '/(app)/(admin)/returns/[id]', web: '/admin/returns/[id]', surface: 'admin', status: 'ported' },
  { mobile: '/(app)/(admin)/returns', web: '/admin/returns', surface: 'admin', status: 'ported' },
  { mobile: '/(app)/(admin)/scheduling', web: '/admin/production/scheduling', surface: 'admin', status: 'ported' },
  { mobile: '/(app)/(admin)/users', web: '/admin/employees', surface: 'admin', status: 'ported' },
  { mobile: '/(app)/(admin)/users/staff-types/[id]', web: '/admin/employees/staff-types/[id]', surface: 'admin', status: 'ported' },
  { mobile: '/(app)/(admin)/users/staff-types', web: '/admin/employees/staff-types', surface: 'admin', status: 'ported' },
  { mobile: '/(app)/(admin)/users/staff-types/new', web: '/admin/employees/staff-types', surface: 'admin', status: 'ported' },
  { mobile: '/(app)/(customer)/(tabs)/account', web: '/dealer/profile', surface: 'dealer', status: 'ported' },
  { mobile: '/(app)/(customer)/(tabs)/basket', web: '/dealer/basket', surface: 'dealer', status: 'ported' },
  { mobile: '/(app)/(customer)/(tabs)/catalog', web: '/dealer/catalog', surface: 'dealer', status: 'ported' },
  { mobile: '/(app)/(customer)/(tabs)', web: '/dealer/dashboard', surface: 'dealer', status: 'ported' },
  { mobile: '/(app)/(customer)/(tabs)/new-order', web: '/dealer/new-order', surface: 'dealer', status: 'ported' },
  { mobile: '/(app)/(customer)/(tabs)/orders', web: '/dealer/orders', surface: 'dealer', status: 'ported' },
  { mobile: '/(app)/(customer)/(tabs)/schedule', web: '/dealer/deliveries', surface: 'dealer', status: 'ported' },
  { mobile: '/(app)/(customer)/account/calendar', web: '/dealer/account/calendar', surface: 'dealer', status: 'ported' },
  { mobile: '/(app)/(customer)/account/notifications', web: '/dealer/account/notifications', surface: 'dealer', status: 'ported' },
  { mobile: '/(app)/(customer)/account/payments', web: '/dealer/account/payments', surface: 'dealer', status: 'ported' },
  { mobile: '/(app)/(customer)/account/security', web: '/dealer/account/security', surface: 'dealer', status: 'ported' },
  { mobile: '/(app)/(customer)/account/statement', web: '/dealer/account/statement', surface: 'dealer', status: 'ported' },
  { mobile: '/(app)/(customer)/ai-chat', web: '/dealer/ai-chat', surface: 'dealer', status: 'ported' },
  { mobile: '/(app)/(customer)/catalog/[id]/customize', web: '/dealer/catalog/[id]/customize', surface: 'dealer', status: 'ported' },
  { mobile: '/(app)/(customer)/catalog/[id]', web: '/dealer/catalog/[id]', surface: 'dealer', status: 'ported' },
  { mobile: '/(app)/(customer)/deliveries/[id]', web: '/dealer/deliveries/[id]', surface: 'dealer', status: 'ported' },
  { mobile: '/(app)/(customer)/deliveries', web: '/dealer/deliveries', surface: 'dealer', status: 'ported' },
  { mobile: '/(app)/(customer)/invoices/[id]', web: '/dealer/invoices/[id]', surface: 'dealer', status: 'ported' },
  { mobile: '/(app)/(customer)/invoices', web: '/dealer/invoices', surface: 'dealer', status: 'ported' },
  { mobile: '/(app)/(customer)/order/custom', web: '/dealer/order/custom', surface: 'dealer', status: 'ported' },
  { mobile: '/(app)/(customer)/orders/[id]/flow', web: '/dealer/orders/[id]/flow', surface: 'dealer', status: 'ported' },
  { mobile: '/(app)/(customer)/orders/[id]', web: '/dealer/orders/[id]', surface: 'dealer', status: 'ported' },
  { mobile: '/(app)/(customer)/quotations/[id]', web: '/dealer/quotations/[id]', surface: 'dealer', status: 'ported' },
  { mobile: '/(app)/(customer)/quotations', web: '/dealer/quotations', surface: 'dealer', status: 'ported' },
  { mobile: '/(app)/(customer)/requests/[id]', web: '/dealer/requests/[id]', surface: 'dealer', status: 'ported' },
  { mobile: '/(app)/(customer)/returns/[id]', web: '/dealer/returns/[id]', surface: 'dealer', status: 'ported' },
  { mobile: '/(app)/(customer)/returns/create', web: '/dealer/returns/create', surface: 'dealer', status: 'ported' },
  { mobile: '/(app)/(customer)/returns', web: '/dealer/returns', surface: 'dealer', status: 'ported' },
  { mobile: '/(app)/(employee)/(tabs)/completed', web: '/worker/tasks/completed', surface: 'worker', status: 'ported' },
  { mobile: '/(app)/(employee)/(tabs)', web: '/worker/dashboard', surface: 'worker', status: 'ported' },
  { mobile: '/(app)/(employee)/(tabs)/notifications', web: '/worker/notifications', surface: 'worker', status: 'ported' },
  { mobile: '/(app)/(employee)/(tabs)/profile', web: '/worker/profile', surface: 'worker', status: 'ported' },
  { mobile: '/(app)/(employee)/(tabs)/tasks', web: '/worker/tasks', surface: 'worker', status: 'ported' },
  { mobile: '/(app)/(employee)/completed-orders/[salesOrderId]', web: '/worker/completed-orders/[salesOrderId]', surface: 'worker', status: 'ported' },
  { mobile: '/(app)/(employee)/deliveries/[id]', web: '/worker/deliveries/[id]', surface: 'worker', status: 'ported' },
  { mobile: '/(app)/(employee)/lane/[id]', web: '/worker/lane/[id]', surface: 'worker', status: 'ported' },
  { mobile: '/(app)/(employee)/orders/[salesOrderId]', web: '/worker/orders/[salesOrderId]', surface: 'worker', status: 'ported' },
  { mobile: '/(app)/(employee)/profile/notifications', web: '/worker/profile/notifications', surface: 'worker', status: 'ported' },
  { mobile: '/(app)/(employee)/tasks/[id]', web: '/worker/tasks/[id]', surface: 'worker', status: 'ported' },
  { mobile: '/(app)/(employee)/tasks/[id]/take-in', web: '/worker/tasks/[id]/take-in', surface: 'worker', status: 'ported' },
  { mobile: '/(app)/_forbidden', web: '/admin/dashboard', surface: 'shared', status: 'ported' },
  { mobile: '/(app)', web: '/admin/dashboard', surface: 'shared', status: 'ported' },
  { mobile: '/(app)/notifications', web: '/admin/notifications', surface: 'shared', status: 'ported' },
  { mobile: '/(app)/search', web: '/admin/search', surface: 'shared', status: 'ported' },
  { mobile: '/(auth)/disabled', web: '/disabled', surface: 'auth', status: 'ported' },
  { mobile: '/(auth)/login', web: '/login', surface: 'auth', status: 'ported' },
  { mobile: '/(auth)/mfa', web: '/mfa', surface: 'auth', status: 'ported' },
  { mobile: '/(auth)/offline', web: null, surface: 'auth', status: 'intentionally-native-only' },
  { mobile: '/(auth)/session-expired', web: '/session-expired', surface: 'auth', status: 'ported' },
  { mobile: '/(auth)/unlock', web: null, surface: 'auth', status: 'intentionally-native-only' },
];


export function mobileRouteKey(filePath: string): string | null {
  const match = filePath.match(/apps\/mobile\/app\/(.+)\.tsx$/);
  const captured = match?.[1];
  if (!captured) return null;
  let rel = captured.replace(/\\/g, '/');
  if (rel.includes('_layout')) return null;
  rel = rel.replace(/\/index$/, '');
  return `/${rel}`.replace(/\/+/g, '/').replace(/\/$/, '') || '/';
}

