import type { Permission } from '@maher/permissions';
import type {
  LocaleCopy,
  NotificationEntityType,
  TopicAudience,
  TopicDefinition,
  TopicGroup,
  TopicUrgency,
} from './types';

function L(en: string, ar: string, he: string): LocaleCopy {
  return { en, ar, he };
}

type Spec = {
  code: string;
  group: TopicGroup;
  audiences: readonly TopicAudience[];
  permission?: Permission | readonly Permission[];
  defaultOn?: boolean;
  urgency?: TopicUrgency;
  entity: NotificationEntityType;
  templateCode: string;
  name: LocaleCopy;
  hint: LocaleCopy;
  pushTitle: LocaleCopy;
  pushBody: LocaleCopy;
};

function topic(spec: Spec): TopicDefinition {
  return {
    ...spec,
    defaultOn: spec.defaultOn ?? true,
    urgency: spec.urgency ?? 'normal',
  };
}

export const TOPIC_GROUP_LABELS: Record<TopicGroup, LocaleCopy> = {
  commercial: L('Orders & quotes', 'الطلبات والعروض', 'הזמנות והצעות'),
  factory: L('Factory floor', 'أرض المصنع', 'רצפת הייצור'),
  quality: L('Quality', 'الجودة', 'איכות'),
  delivery: L('Delivery', 'التسليم', 'משלוח'),
  inventory: L('Inventory', 'المخزون', 'מלאי'),
  purchasing: L('Purchasing', 'المشتريات', 'רכש'),
  returns: L('Returns', 'المرتجعات', 'החזרות'),
  finance: L('Invoices & payments', 'الفواتير والدفع', 'חשבוניות ותשלומים'),
  schedule: L('Scheduling', 'الجدولة', 'תזמון'),
  people: L('People', 'الأشخاص', 'אנשים'),
};

const TOPICS_LIST: TopicDefinition[] = [
  topic({
    code: 'request.submitted',
    group: 'commercial',
    audiences: ['staff'],
    permission: 'request.read',
    entity: 'request',
    templateCode: 'NEW_ORDER',
    name: L('New request', 'طلب جديد', 'בקשה חדשה'),
    hint: L('A dealer submitted a new request.', 'قدّم التاجر طلباً جديداً.', 'הסוחר הגיש בקשה חדשה.'),
    pushTitle: L('New request', 'طلب جديد', 'בקשה חדשה'),
    pushBody: L('{number} needs review.', '{number} بانتظار المراجعة.', '{number} ממתינה לבדיקה.'),
  }),
  topic({
    code: 'request.needsInfo',
    group: 'commercial',
    audiences: ['dealer', 'staff'],
    permission: 'request.read',
    entity: 'request',
    templateCode: 'ORDER_NEEDS_INFORMATION',
    name: L('Request needs information', 'الطلب يحتاج معلومات', 'הבקשה דורשת מידע'),
    hint: L('Factory asked for more details.', 'طلب المصنع تفاصيل إضافية.', 'המפעל ביקש פרטים נוספים.'),
    pushTitle: L('More information needed', 'نحتاج معلومات إضافية', 'נדרש מידע נוסף'),
    pushBody: L('Request {number} needs a reply.', 'الطلب {number} بانتظار ردك.', 'בקשה {number} ממתינה לתשובה.'),
  }),
  topic({
    code: 'request.quoted',
    group: 'commercial',
    audiences: ['dealer', 'staff'],
    permission: 'quotation.read',
    entity: 'request',
    templateCode: 'REQUEST_QUOTED',
    name: L('Request quoted', 'تم تسعير الطلب', 'הבקשה תומחרה'),
    hint: L('The request moved to quoted.', 'انتقل الطلب إلى مرحلة العرض.', 'הבקשה עברה להצעת מחיר.'),
    pushTitle: L('Request quoted', 'تم تسعير الطلب', 'הבקשה תומחרה'),
    pushBody: L('{number} now has a quotation.', '{number} أصبح له عرض سعر.', 'ל-{number} יש כעת הצעת מחיר.'),
  }),
  topic({
    code: 'inbound.emailRfq',
    group: 'commercial',
    audiences: ['staff'],
    permission: ['request.read', 'ai-intake.read'],
    entity: 'request',
    templateCode: 'INBOUND_EMAIL_RFQ',
    name: L('Inbound email request', 'طلب من البريد', 'בקשה מדואר נכנס'),
    hint: L('A request arrived by email.', 'وصل طلب عبر البريد.', 'הגיעה בקשה בדוא״ל.'),
    pushTitle: L('Email request', 'طلب بالبريد', 'בקשת דוא״ל'),
    pushBody: L('{number} arrived by email.', 'وصل {number} عبر البريد.', '{number} הגיעה בדוא״ל.'),
  }),
  topic({
    code: 'inbound.whatsappRfq',
    group: 'commercial',
    audiences: ['staff'],
    permission: ['request.read', 'ai-intake.read'],
    entity: 'request',
    templateCode: 'INBOUND_WHATSAPP_RFQ',
    name: L('Inbound WhatsApp request', 'طلب من واتساب', 'בקשה מוואטסאפ'),
    hint: L('A request arrived on WhatsApp.', 'وصل طلب عبر واتساب.', 'הגיעה בקשה בוואטסאפ.'),
    pushTitle: L('WhatsApp request', 'طلب واتساب', 'בקשת וואטסאפ'),
    pushBody: L('{number} arrived on WhatsApp.', 'وصل {number} عبر واتساب.', '{number} הגיעה בוואטסאפ.'),
  }),
  topic({
    code: 'ai.draftReady',
    group: 'commercial',
    audiences: ['staff'],
    permission: 'ai-intake.read',
    entity: 'aiIntake',
    templateCode: 'AI_DRAFT_READY',
    name: L('AI draft ready', 'مسودة الذكاء جاهزة', 'טיוטת AI מוכנה'),
    hint: L('An extraction draft is ready to review.', 'مسودة الاستخراج جاهزة للمراجعة.', 'טיוטת החילוץ מוכנה לבדיקה.'),
    pushTitle: L('AI draft ready', 'مسودة جاهزة', 'טיוטת AI מוכנה'),
    pushBody: L('{jobNumber} is ready for review.', '{jobNumber} جاهزة للمراجعة.', '{jobNumber} מוכנה לבדיקה.'),
  }),
  topic({
    code: 'quote.sent',
    group: 'commercial',
    audiences: ['dealer', 'staff'],
    permission: 'quotation.read',
    entity: 'quotation',
    templateCode: 'QUOTE_SENT',
    name: L('Quotation sent', 'إرسال عرض السعر', 'הצעת מחיר נשלחה'),
    hint: L('A quotation was sent to the dealer.', 'أُرسل عرض سعر للتاجر.', 'נשלחה הצעת מחיר לסוחר.'),
    pushTitle: L('New quotation', 'عرض سعر جديد', 'הצעת מחיר חדשה'),
    pushBody: L('Quotation {number} was sent.', 'أُرسل عرض السعر {number}.', 'הצעת מחיר {number} נשלחה.'),
  }),
  topic({
    code: 'quote.accepted',
    group: 'commercial',
    audiences: ['staff'],
    permission: 'quotation.read',
    entity: 'quotation',
    templateCode: 'QUOTE_ACCEPTED',
    name: L('Quotation accepted', 'قبول عرض السعر', 'הצעת מחיר התקבלה'),
    hint: L('A dealer accepted a quotation.', 'قبل التاجر عرض السعر.', 'הסוחר קיבל את הצעת המחיר.'),
    pushTitle: L('Quotation accepted', 'قُبل عرض السعر', 'הצעת מחיר התקבלה'),
    pushBody: L('{number} was accepted.', 'قُبل {number}.', '{number} התקבלה.'),
  }),
  topic({
    code: 'quote.rejected',
    group: 'commercial',
    audiences: ['staff'],
    permission: 'quotation.read',
    entity: 'quotation',
    templateCode: 'QUOTE_REJECTED',
    name: L('Quotation rejected', 'رفض عرض السعر', 'הצעת מחיר נדחתה'),
    hint: L('A dealer rejected a quotation.', 'رفض التاجر عرض السعر.', 'הסוחר דחה את הצעת המחיר.'),
    pushTitle: L('Quotation rejected', 'رُفض عرض السعر', 'הצעת מחיר נדחתה'),
    pushBody: L('{number} was rejected.', 'رُفض {number}.', '{number} נדחתה.'),
  }),
  topic({
    code: 'quote.revisionRequested',
    group: 'commercial',
    audiences: ['staff'],
    permission: 'quotation.read',
    entity: 'quotation',
    templateCode: 'QUOTE_REVISION_REQUESTED',
    name: L('Quotation revision requested', 'طلب تعديل العرض', 'בקשת תיקון להצעה'),
    hint: L('A dealer asked to revise a quotation.', 'طلب التاجر تعديل العرض.', 'הסוחר ביקש לתקן את ההצעה.'),
    pushTitle: L('Revision requested', 'طلب تعديل', 'בקשת תיקון'),
    pushBody: L('{number} needs a revision.', '{number} يحتاج تعديلاً.', '{number} דורשת תיקון.'),
  }),
  topic({
    code: 'quote.expired',
    group: 'commercial',
    audiences: ['dealer', 'staff'],
    permission: 'quotation.read',
    defaultOn: false,
    entity: 'quotation',
    templateCode: 'QUOTE_EXPIRED',
    name: L('Quotation expired', 'انتهاء عرض السعر', 'הצעת מחיר פגה'),
    hint: L('A quotation reached its validity date.', 'انتهت صلاحية عرض السعر.', 'פג תוקף הצעת המחיר.'),
    pushTitle: L('Quotation expired', 'انتهى عرض السعر', 'הצעת מחיר פגה'),
    pushBody: L('{number} is no longer valid.', '{number} لم يعد صالحاً.', '{number} אינה בתוקף.'),
  }),
  topic({
    code: 'order.confirmed',
    group: 'commercial',
    audiences: ['dealer', 'staff'],
    permission: ['sales-order.read', 'production-order.read'],
    entity: 'salesOrder',
    templateCode: 'ORDER_CONFIRMED',
    name: L('Order confirmed', 'تأكيد الطلبية', 'הזמנה אושרה'),
    hint: L('A sales order was confirmed.', 'تم تأكيد طلبية البيع.', 'הזמנת מכירה אושרה.'),
    pushTitle: L('Order confirmed', 'تم تأكيد الطلبية', 'הזמנה אושרה'),
    pushBody: L('{number} is confirmed.', 'تم تأكيد {number}.', '{number} אושרה.'),
  }),
  topic({
    code: 'order.setupRequired',
    group: 'commercial',
    audiences: ['dealer', 'staff'],
    permission: 'production.setup.view',
    entity: 'salesOrder',
    templateCode: 'ORDER_PRODUCTION_SETUP',
    name: L('Production setup needed', 'يلزم إعداد الإنتاج', 'נדרשת הכנת ייצור'),
    hint: L('The factory is preparing production.', 'المصنع يعدّ الإنتاج.', 'המפעל מכין את הייצור.'),
    pushTitle: L('Production setup', 'إعداد الإنتاج', 'הכנת ייצור'),
    pushBody: L('{number} is in production setup.', '{number} في إعداد الإنتاج.', '{number} בהכנת ייצור.'),
  }),
  topic({
    code: 'order.setupReleased',
    group: 'commercial',
    audiences: ['staff'],
    permission: 'production.setup.view',
    entity: 'salesOrder',
    templateCode: 'ORDER_SETUP_RELEASED',
    name: L('Production setup released', 'إطلاق إعداد الإنتاج', 'הכנת הייצור שוחררה'),
    hint: L('Setup was released to the floor.', 'أُطلق الإعداد إلى الأرض.', 'ההכנה שוחררה לרצפה.'),
    pushTitle: L('Setup released', 'أُطلق الإعداد', 'ההכנה שוחררה'),
    pushBody: L('{number} is released to production.', 'أُطلق {number} للإنتاج.', '{number} שוחררה לייצור.'),
  }),
  topic({
    code: 'order.waitingMaterials',
    group: 'commercial',
    audiences: ['dealer', 'staff'],
    permission: 'production-order.read',
    entity: 'salesOrder',
    templateCode: 'ORDER_WAITING_MATERIALS',
    name: L('Waiting for materials', 'بانتظار المواد', 'ממתין לחומרים'),
    hint: L('The order is waiting on materials.', 'الطلبية تنتظر المواد.', 'ההזמנה ממתינה לחומרים.'),
    pushTitle: L('Waiting for materials', 'بانتظار المواد', 'ממתין לחומרים'),
    pushBody: L('{number} is waiting on materials.', '{number} تنتظر المواد.', '{number} ממתינה לחומרים.'),
  }),
  topic({
    code: 'order.readyForProduction',
    group: 'commercial',
    audiences: ['dealer', 'staff', 'worker'],
    permission: ['production-order.read', 'production-task.read'],
    entity: 'salesOrder',
    templateCode: 'ORDER_READY_FOR_PRODUCTION',
    name: L('Ready for production', 'جاهز للإنتاج', 'מוכן לייצור'),
    hint: L('The order can start on the floor.', 'يمكن بدء الطلبية على الأرض.', 'אפשר להתחיל את ההזמנה ברצפה.'),
    pushTitle: L('Ready for production', 'جاهز للإنتاج', 'מוכן לייצור'),
    pushBody: L('{number} is ready for the floor.', '{number} جاهزة للأرض.', '{number} מוכנה לרצפה.'),
  }),
  topic({
    code: 'order.inProduction',
    group: 'commercial',
    audiences: ['dealer', 'staff'],
    permission: 'production-order.read',
    defaultOn: false,
    entity: 'salesOrder',
    templateCode: 'ORDER_IN_PRODUCTION',
    name: L('In production', 'قيد الإنتاج', 'בייצור'),
    hint: L('The order started on the floor.', 'بدأت الطلبية على الأرض.', 'ההזמנה התחילה ברצפה.'),
    pushTitle: L('In production', 'قيد الإنتاج', 'בייצור'),
    pushBody: L('{number} is in production.', '{number} قيد الإنتاج.', '{number} בייצור.'),
  }),
  topic({
    code: 'order.readyForDelivery',
    group: 'commercial',
    audiences: ['dealer', 'staff', 'worker'],
    permission: ['production-order.read', 'delivery.read'],
    urgency: 'high',
    entity: 'salesOrder',
    templateCode: 'ORDER_READY_FOR_DELIVERY',
    name: L('Ready for delivery', 'جاهز للتسليم', 'מוכן למשלוח'),
    hint: L('The order is packed and ready.', 'الطلبية معبأة وجاهزة.', 'ההזמנה ארוזה ומוכנה.'),
    pushTitle: L('Ready for delivery', 'جاهز للتسليم', 'מוכן למשלוח'),
    pushBody: L('{number} is ready to ship.', '{number} جاهزة للشحن.', '{number} מוכנה למשלוח.'),
  }),
  topic({
    code: 'order.onHold',
    group: 'commercial',
    audiences: ['dealer', 'staff', 'worker'],
    permission: ['sales-order.read', 'production-order.read', 'production-task.read'],
    urgency: 'high',
    entity: 'salesOrder',
    templateCode: 'ORDER_ON_HOLD',
    name: L('Order on hold', 'الطلبية معلّقة', 'הזמנה בהשהיה'),
    hint: L('The order was put on hold.', 'تم تعليق الطلبية.', 'ההזמנה הושהתה.'),
    pushTitle: L('Order on hold', 'الطلبية معلّقة', 'הזמנה בהשהיה'),
    pushBody: L('{number} is on hold.', '{number} معلّقة.', '{number} בהשהיה.'),
  }),
  topic({
    code: 'order.resumed',
    group: 'commercial',
    audiences: ['dealer', 'staff', 'worker'],
    permission: ['sales-order.read', 'production-order.read', 'production-task.read'],
    entity: 'salesOrder',
    templateCode: 'ORDER_RESUMED',
    name: L('Order resumed', 'استئناف الطلبية', 'ההזמנה חודשה'),
    hint: L('A held order was resumed.', 'تم استئناف طلبية معلّقة.', 'הזמנה מושהית חודשה.'),
    pushTitle: L('Order resumed', 'استُؤنفت الطلبية', 'ההזמנה חודשה'),
    pushBody: L('{number} is moving again.', '{number} عادت للحركة.', '{number} חזרה לנוע.'),
  }),
  topic({
    code: 'order.cancelled',
    group: 'commercial',
    audiences: ['dealer', 'staff', 'worker'],
    permission: ['sales-order.read', 'production-order.read', 'production-task.read'],
    urgency: 'high',
    entity: 'salesOrder',
    templateCode: 'ORDER_CANCELLED',
    name: L('Order cancelled', 'إلغاء الطلبية', 'הזמנה בוטלה'),
    hint: L('The order was cancelled.', 'أُلغيت الطلبية.', 'ההזמנה בוטלה.'),
    pushTitle: L('Order cancelled', 'أُلغيت الطلبية', 'הזמנה בוטלה'),
    pushBody: L('{number} was cancelled.', 'أُلغي {number}.', '{number} בוטלה.'),
  }),
  topic({
    code: 'order.deliveryDateConfirmed',
    group: 'schedule',
    audiences: ['dealer', 'staff'],
    permission: 'schedule.read',
    entity: 'salesOrder',
    templateCode: 'DELIVERY_DATE_CONFIRMED',
    name: L('Delivery date confirmed', 'تأكيد تاريخ التسليم', 'תאריך אספקה אושר'),
    hint: L('A delivery date was confirmed.', 'تم تأكيد تاريخ التسليم.', 'תאריך אספקה אושר.'),
    pushTitle: L('Delivery date confirmed', 'تأكيد تاريخ التسليم', 'תאריך אספקה אושר'),
    pushBody: L('{number}: {date}.', '{number}: {date}.', '{number}: {date}.'),
  }),
  topic({
    code: 'order.deliveryDateUpdated',
    group: 'schedule',
    audiences: ['dealer', 'staff'],
    permission: 'schedule.read',
    entity: 'salesOrder',
    templateCode: 'DELIVERY_DATE_UPDATED',
    name: L('Delivery date updated', 'تحديث تاريخ التسليم', 'תאריך אספקה עודכן'),
    hint: L('The expected delivery date changed.', 'تغيّر تاريخ التسليم المتوقع.', 'תאריך האספקה הצפוי השתנה.'),
    pushTitle: L('Delivery date updated', 'تحديث تاريخ التسليم', 'תאריך אספקה עודכן'),
    pushBody: L('{number} moved to {date}.', '{number} إلى {date}.', '{number} עברה ל-{date}.'),
  }),
  topic({
    code: 'order.deliveryMayBeDelayed',
    group: 'schedule',
    audiences: ['dealer', 'staff'],
    permission: 'schedule.read',
    urgency: 'high',
    entity: 'salesOrder',
    templateCode: 'DELIVERY_MAY_BE_DELAYED',
    name: L('Delivery may be delayed', 'قد يتأخر التسليم', 'ייתכן עיכוב באספקה'),
    hint: L('Production is running long on this order.', 'الإنتاج يستغرق وقتاً أطول.', 'הייצור אורך יותר מהצפוי.'),
    pushTitle: L('Delivery may be delayed', 'قد يتأخر التسليم', 'ייתכן עיכוב באספקה'),
    pushBody: L('{number} may arrive later. Confirmed date remains {date}.', '{number} قد يتأخر. التاريخ المؤكد {date}.', '{number} עלולה לאחר. התאריך המאושר {date}.'),
  }),
  topic({
    code: 'task.assigned',
    group: 'factory',
    audiences: ['worker', 'staff'],
    permission: ['production-task.read', 'production-order.assign'],
    entity: 'task',
    templateCode: 'WORKER_ASSIGNED',
    name: L('Task assigned', 'تعيين مهمة', 'משימה הוקצתה'),
    hint: L('A task was assigned to you.', 'عُيّنت لك مهمة.', 'הוקצתה לכם משימה.'),
    pushTitle: L('Task assigned', 'مهمة جديدة', 'משימה הוקצתה'),
    pushBody: L('{taskName} on {number}.', '{taskName} على {number}.', '{taskName} ב-{number}.'),
  }),
  topic({
    code: 'task.unassigned',
    group: 'factory',
    audiences: ['worker', 'staff'],
    permission: ['production-task.read', 'production-order.assign'],
    defaultOn: false,
    entity: 'task',
    templateCode: 'TASK_UNASSIGNED',
    name: L('Task unassigned', 'إلغاء تعيين المهمة', 'הקצאת משימה בוטלה'),
    hint: L('A task was removed from you.', 'أُزيلت مهمة منك.', 'משימה הוסרה מכם.'),
    pushTitle: L('Task unassigned', 'أُلغيت المهمة', 'הקצאה בוטלה'),
    pushBody: L('{taskName} is no longer yours.', '{taskName} لم تعد لك.', '{taskName} כבר אינה שלכם.'),
  }),
  topic({
    code: 'task.urgent',
    group: 'factory',
    audiences: ['worker', 'staff'],
    permission: ['production-task.read', 'production-task.update-any'],
    urgency: 'high',
    entity: 'task',
    templateCode: 'URGENT_TASK',
    name: L('Urgent task', 'مهمة عاجلة', 'משימה דחופה'),
    hint: L('A task was marked urgent.', 'عُلّمت مهمة كعاجلة.', 'משימה סומנה כדחופה.'),
    pushTitle: L('Urgent task', 'مهمة عاجلة', 'משימה דחופה'),
    pushBody: L('{taskName} ({number}).', '{taskName} ({number}).', '{taskName} ({number}).'),
  }),
  topic({
    code: 'task.scheduledToday',
    group: 'factory',
    audiences: ['worker'],
    permission: 'production-task.read',
    entity: 'task',
    templateCode: 'TASK_SCHEDULED_TODAY',
    name: L('Scheduled today', 'مجدولة اليوم', 'מתוזמנת להיום'),
    hint: L('You have a task planned for today.', 'لديك مهمة مجدولة اليوم.', 'יש לכם משימה להיום.'),
    pushTitle: L('Today’s task', 'مهمة اليوم', 'משימת היום'),
    pushBody: L('{taskName} on {number}.', '{taskName} على {number}.', '{taskName} ב-{number}.'),
  }),
  topic({
    code: 'task.ready',
    group: 'factory',
    audiences: ['worker', 'staff'],
    permission: ['production-task.read', 'production-order.read'],
    defaultOn: true,
    entity: 'task',
    templateCode: 'TASK_READY',
    name: L('Task ready', 'المهمة جاهزة', 'משימה מוכנה'),
    hint: L('A task became ready — including after the previous stage.', 'أصبحت المهمة جاهزة — بما فيها بعد المرحلة السابقة.', 'משימה הפכה למוכנה — גם אחרי השלב הקודם.'),
    pushTitle: L('{taskName} is ready', '{taskName} جاهزة', '{taskName} מוכנה'),
    pushBody: L('{number} · Your next task is ready to start.', '{number} · مهمتك التالية جاهزة للبدء.', '{number} · המשימה הבאה מוכנה להתחלה.'),
  }),
  topic({
    code: 'task.started',
    group: 'factory',
    audiences: ['staff'],
    permission: 'production-order.read',
    defaultOn: false,
    entity: 'task',
    templateCode: 'TASK_STARTED',
    name: L('Task started', 'بدء المهمة', 'משימה התחילה'),
    hint: L('Someone started a floor task.', 'بدأ أحدهم مهمة على الأرض.', 'מישהו התחיל משימה ברצפה.'),
    pushTitle: L('Task started', 'بدأت المهمة', 'משימה התחילה'),
    pushBody: L('{taskName} on {number}.', '{taskName} على {number}.', '{taskName} ב-{number}.'),
  }),
  topic({
    code: 'task.paused',
    group: 'factory',
    audiences: ['staff'],
    permission: 'production-order.read',
    defaultOn: false,
    entity: 'task',
    templateCode: 'TASK_PAUSED',
    name: L('Task paused', 'إيقاف المهمة', 'משימה הושהתה'),
    hint: L('A floor task was paused.', 'أُوقفت مهمة على الأرض.', 'משימה ברצפה הושהתה.'),
    pushTitle: L('Task paused', 'أُوقفت المهمة', 'משימה הושהתה'),
    pushBody: L('{taskName} on {number}.', '{taskName} على {number}.', '{taskName} ב-{number}.'),
  }),
  topic({
    code: 'task.resumed',
    group: 'factory',
    audiences: ['staff', 'worker'],
    permission: ['production-order.read', 'production-task.read'],
    defaultOn: false,
    entity: 'task',
    templateCode: 'TASK_RESUMED',
    name: L('Task resumed', 'استئناف المهمة', 'משימה חודשה'),
    hint: L('A paused task started again.', 'استُؤنفت مهمة متوقفة.', 'משימה מושהית חודשה.'),
    pushTitle: L('Task resumed', 'استُؤنفت المهمة', 'משימה חודשה'),
    pushBody: L('{taskName} on {number}.', '{taskName} على {number}.', '{taskName} ב-{number}.'),
  }),
  topic({
    code: 'task.completed',
    group: 'factory',
    audiences: ['staff'],
    permission: 'production-order.read',
    entity: 'task',
    templateCode: 'TASK_COMPLETED',
    name: L('Task completed', 'اكتمال المهمة', 'משימה הושלמה'),
    hint: L('A floor task was completed.', 'اكتملت مهمة على الأرض.', 'משימה ברצפה הושלמה.'),
    pushTitle: L('Task completed', 'اكتملت المهمة', 'משימה הושלמה'),
    pushBody: L('{taskName} on {number}.', '{taskName} على {number}.', '{taskName} ב-{number}.'),
  }),
  topic({
    code: 'stage.completed',
    group: 'factory',
    audiences: ['worker', 'staff'],
    permission: ['production-task.read', 'production-order.read'],
    entity: 'productionOrder',
    templateCode: 'STAGE_COMPLETED',
    name: L('Stage completed', 'اكتمال المرحلة', 'שלב הושלם'),
    hint: L('A stage finished; the next stage may be ready.', 'انتهت مرحلة؛ التالية قد تكون جاهزة.', 'שלב הסתיים; ייתכן שהבא מוכן.'),
    pushTitle: L('Stage done', 'انتهت المرحلة', 'השלב הסתיים'),
    pushBody: L('{stage} done on {number}. Next: {nextStage}.', 'انتهت {stage} على {number}. التالية: {nextStage}.', '{stage} הסתיים ב-{number}. הבא: {nextStage}.'),
  }),
  topic({
    code: 'wip.readyToTakeIn',
    group: 'factory',
    audiences: ['worker', 'staff'],
    permission: ['production-task.read', 'inventory.read'],
    entity: 'wip',
    templateCode: 'WIP_READY_TO_TAKE_IN',
    name: L('WIP ready to take in', 'نصف مصنع جاهز للاستلام', 'WIP מוכן לקליטה'),
    hint: L('Semi-finished work arrived at your stage.', 'وصل عمل نصف مصنع إلى مرحلتك.', 'עבודה חצי-גמורה הגיעה לשלב שלכם.'),
    pushTitle: L('Ready to take in', 'جاهز للاستلام', 'מוכן לקליטה'),
    pushBody: L('{number} is waiting at your bench.', '{number} بانتظارك على الطاولة.', '{number} ממתינה על השולחן שלכם.'),
  }),
  topic({
    code: 'wip.handoffMismatch',
    group: 'factory',
    audiences: ['worker', 'staff'],
    permission: ['production-task.read', 'production-order.read'],
    urgency: 'high',
    entity: 'wip',
    templateCode: 'WIP_HANDOFF_MISMATCH',
    name: L('WIP handoff mismatch', 'عدم تطابق تسليم نصف المصنع', 'אי-התאמה במסירת WIP'),
    hint: L('Piece or count mismatch on a handoff.', 'عدم تطابق القطع أو العدد عند التسليم.', 'אי-התאמה בפריטים או בכמות במסירה.'),
    pushTitle: L('Handoff mismatch', 'عدم تطابق التسليم', 'אי-התאמה במסירה'),
    pushBody: L('{number} needs a count check.', '{number} تحتاج مراجعة العدد.', '{number} דורשת בדיקת כמות.'),
  }),
  topic({
    code: 'blocker.opened',
    group: 'factory',
    audiences: ['staff'],
    permission: 'production-order.read',
    urgency: 'high',
    entity: 'blocker',
    templateCode: 'PRODUCTION_PROBLEM_OPENED',
    name: L('Production problem opened', 'بلاغ مشكلة إنتاج', 'נפתחה בעיית ייצור'),
    hint: L('A worker reported a floor problem.', 'بلّغ عامل عن مشكلة على الأرض.', 'עובד דיווח על בעיה ברצפה.'),
    pushTitle: L('Floor problem', 'مشكلة على الأرض', 'בעיה ברצפה'),
    pushBody: L('{number} / {taskName} needs a look.', '{number} / {taskName} تحتاج نظرة.', '{number} / {taskName} דורשת מבט.'),
  }),
  topic({
    code: 'blocker.answered',
    group: 'factory',
    audiences: ['worker', 'staff'],
    permission: ['production-task.read', 'production-order.read'],
    entity: 'blocker',
    templateCode: 'PRODUCTION_PROBLEM_ANSWERED',
    name: L('Problem answered', 'رد على المشكلة', 'תשובה לבעיה'),
    hint: L('A supervisor answered a floor problem.', 'رد المشرف على مشكلة الأرض.', 'מנהל ענה לבעיה ברצפה.'),
    pushTitle: L('Problem answered', 'رد على المشكلة', 'תשובה לבעיה'),
    pushBody: L('{number} / {taskName} has a reply.', '{number} / {taskName} فيها رد.', '{number} / {taskName} קיבלה תשובה.'),
  }),
  topic({
    code: 'execution.ripple',
    group: 'schedule',
    audiences: ['staff'],
    permission: 'schedule.manage',
    defaultOn: false,
    entity: 'schedule',
    templateCode: 'EXECUTION_RIPPLE',
    name: L('Schedule shifted', 'تعديل الجدول', 'הלוח זז'),
    hint: L('Actual time on the floor shifted the plan.', 'الوقت الفعلي على الأرض حرّك الخطة.', 'זמן בפועל ברצפה הזיז את התוכנית.'),
    pushTitle: L('Schedule shifted', 'تعديل الجدول', 'הלוח זז'),
    pushBody: L('{number} plan was updated.', 'حُدّثت خطة {number}.', 'תוכנית {number} עודכנה.'),
  }),
  topic({
    code: 'material.overIssue',
    group: 'factory',
    audiences: ['staff'],
    permission: ['production-order.read', 'purchase-order.read'],
    entity: 'task',
    templateCode: 'MATERIAL_OVER_ISSUE',
    name: L('Material over-issue', 'تجاوز كمية المواد', 'חריגת חומר'),
    hint: L('More material was used than planned.', 'استُخدم من المادة أكثر من المخطط.', 'השתמשו בחומר מעבר לתוכנית.'),
    pushTitle: L('Material over-issue', 'تجاوز المواد', 'חריגת חומר'),
    pushBody: L('{sku} on {number}.', '{sku} على {number}.', '{sku} ב-{number}.'),
  }),
  topic({
    code: 'material.underIssue',
    group: 'factory',
    audiences: ['staff'],
    permission: ['production-order.read', 'purchase-order.read'],
    defaultOn: false,
    entity: 'task',
    templateCode: 'MATERIAL_UNDER_ISSUE',
    name: L('Material under-issue', 'استخدام مواد أقل', 'שימוש חסר בחומר'),
    hint: L('Less material was used than planned.', 'استُخدم من المادة أقل من المخطط.', 'השתמשו בחומר פחות מהתוכנית.'),
    pushTitle: L('Material under-issue', 'مواد أقل من المخطط', 'שימוש חסר בחומר'),
    pushBody: L('{sku} on {number}.', '{sku} على {number}.', '{sku} ב-{number}.'),
  }),
  topic({
    code: 'material.extraIssue',
    group: 'factory',
    audiences: ['staff'],
    permission: ['production-order.read', 'purchase-order.read'],
    entity: 'task',
    templateCode: 'MATERIAL_EXTRA_ISSUE',
    name: L('Extra material used', 'مادة إضافية', 'חומר נוסף'),
    hint: L('An unplanned material was added.', 'أُضيفت مادة خارج الخطة.', 'נוסף חומר מחוץ לתוכנית.'),
    pushTitle: L('Extra material', 'مادة إضافية', 'חומר נוסף'),
    pushBody: L('{sku} on {number}.', '{sku} على {number}.', '{sku} ב-{number}.'),
  }),
  topic({
    code: 'quality.queued',
    group: 'quality',
    audiences: ['staff', 'worker'],
    permission: ['quality-inspection.perform', 'quality-inspection.read'],
    entity: 'qualityInspection',
    templateCode: 'QUALITY_QUEUED',
    name: L('Inspection queued', 'بانتظار الفحص', 'בדיקה בתור'),
    hint: L('Work is ready for inspection.', 'العمل جاهز للفحص.', 'העבודה מוכנה לבדיקה.'),
    pushTitle: L('Inspection waiting', 'فحص بانتظارك', 'בדיקה ממתינה'),
    pushBody: L('{number} is ready to inspect.', '{number} جاهزة للفحص.', '{number} מוכנה לבדיקה.'),
  }),
  topic({
    code: 'quality.passed',
    group: 'quality',
    audiences: ['staff', 'worker'],
    permission: ['quality-inspection.read', 'production-order.read'],
    entity: 'qualityInspection',
    templateCode: 'QUALITY_PASSED',
    name: L('Inspection passed', 'نجاح الفحص', 'הבדיקה עברה'),
    hint: L('QC passed this piece or order.', 'نجح الفحص لهذه القطعة أو الطلبية.', 'הבדיקה עברה לפריט או להזמנה.'),
    pushTitle: L('Inspection passed', 'نجح الفحص', 'הבדיקה עברה'),
    pushBody: L('{number} passed inspection.', 'نجح فحص {number}.', '{number} עברה בדיקה.'),
  }),
  topic({
    code: 'quality.failed',
    group: 'quality',
    audiences: ['staff', 'worker'],
    permission: ['quality-inspection.read', 'production-order.read', 'production-task.read'],
    urgency: 'high',
    entity: 'qualityInspection',
    templateCode: 'QUALITY_FAILED',
    name: L('Inspection failed', 'فشل الفحص', 'הבדיקה נכשלה'),
    hint: L('QC failed — the previous stage may need to look.', 'فشل الفحص — قد تحتاج المرحلة السابقة.', 'הבדיקה נכשלה — ייתכן שהשלב הקודם נדרש.'),
    pushTitle: L('Inspection failed', 'فشل الفحص', 'הבדיקה נכשלה'),
    pushBody: L('{number} needs another look.', '{number} تحتاج نظرة أخرى.', '{number} דורשת מבט נוסף.'),
  }),
  topic({
    code: 'quality.reworkRequired',
    group: 'quality',
    audiences: ['staff', 'worker'],
    permission: ['quality-inspection.read', 'production-task.read'],
    urgency: 'high',
    entity: 'qualityInspection',
    templateCode: 'QUALITY_REWORK_REQUIRED',
    name: L('Rework required', 'يلزم إعادة عمل', 'נדרש תיקון'),
    hint: L('QC sent work back for rework.', 'أعاد الفحص العمل للتصحيح.', 'הבדיקה החזירה עבודה לתיקון.'),
    pushTitle: L('Rework required', 'يلزم إعادة عمل', 'נדרש תיקון'),
    pushBody: L('{number} needs attention before it can continue.', '{number} تحتاج متابعة قبل أن تُستكمل.', '{number} דורשת טיפול לפני שאפשר להמשיך.'),
  }),
  topic({
    code: 'quality.reworkReady',
    group: 'quality',
    audiences: ['staff', 'worker'],
    permission: ['quality-inspection.perform', 'production-task.read'],
    entity: 'qualityInspection',
    templateCode: 'QUALITY_REWORK_READY',
    name: L('Rework ready to inspect', 'إعادة العمل جاهزة للفحص', 'תיקון מוכן לבדיקה'),
    hint: L('Reworked pieces are back in the inspection queue.', 'عادت القطع بعد التصحيح لطابور الفحص.', 'פריטים מתוקנים חזרו לתור הבדיקה.'),
    pushTitle: L('Rework ready', 'إعادة العمل جاهزة', 'תיקון מוכן'),
    pushBody: L('{number} is back for inspection.', '{number} عادت للفحص.', '{number} חזרה לבדיקה.'),
  }),
  topic({
    code: 'packaging.ready',
    group: 'factory',
    audiences: ['worker', 'staff'],
    permission: ['production-task.read', 'delivery.read'],
    entity: 'task',
    templateCode: 'PACKAGING_READY',
    name: L('Packaging ready', 'التعبئة جاهزة', 'אריזה מוכנה'),
    hint: L('Work is ready for packaging.', 'العمل جاهز للتعبئة.', 'העבודה מוכנה לאריזה.'),
    pushTitle: L('Packaging ready', 'التعبئة جاهزة', 'אריזה מוכנה'),
    pushBody: L('{number} is ready to pack.', '{number} جاهزة للتعبئة.', '{number} מוכנה לאריזה.'),
  }),
  topic({
    code: 'packaging.completed',
    group: 'factory',
    audiences: ['staff', 'worker'],
    permission: ['production-order.read', 'delivery.read'],
    entity: 'productionOrder',
    templateCode: 'PACKAGING_COMPLETED',
    name: L('Packaging completed', 'اكتملت التعبئة', 'האריזה הושלמה'),
    hint: L('Packaging finished for this order.', 'انتهت التعبئة لهذه الطلبية.', 'האריזה הסתיימה להזמנה זו.'),
    pushTitle: L('Packaging done', 'اكتملت التعبئة', 'האריזה הושלמה'),
    pushBody: L('{number} is packed.', 'تم تعبئة {number}.', '{number} נארזה.'),
  }),
  topic({
    code: 'delivery.planned',
    group: 'delivery',
    audiences: ['staff', 'worker'],
    permission: ['delivery.read', 'delivery.update'],
    entity: 'delivery',
    templateCode: 'DELIVERY_PLANNED',
    name: L('Delivery planned', 'تخطيط التسليم', 'משלוח תוכנן'),
    hint: L('A delivery run was planned.', 'خُطط لمشوار تسليم.', 'תוכננה נסיעת משלוח.'),
    pushTitle: L('Delivery planned', 'تسليم مخطط', 'משלוח תוכנן'),
    pushBody: L('{number} is on a delivery run.', '{number} على مشوار تسليم.', '{number} בנסיעת משלוח.'),
  }),
  topic({
    code: 'delivery.readyToLoad',
    group: 'delivery',
    audiences: ['worker', 'staff'],
    permission: ['delivery.update', 'delivery.read'],
    urgency: 'high',
    entity: 'delivery',
    templateCode: 'DELIVERY_READY_TO_LOAD',
    name: L('Ready to load', 'جاهز للتحميل', 'מוכן להעמסה'),
    hint: L('The truck load sheet is ready.', 'ورقة تحميل الشاحنة جاهزة.', 'גיליון העמסת המשאית מוכן.'),
    pushTitle: L('Ready to load', 'جاهز للتحميل', 'מוכן להעמסה'),
    pushBody: L('{number} is waiting on the dock.', '{number} بانتظارك في الرصيف.', '{number} ממתינה ברציף.'),
  }),
  topic({
    code: 'delivery.departed',
    group: 'delivery',
    audiences: ['dealer', 'staff', 'worker'],
    permission: 'delivery.read',
    entity: 'delivery',
    templateCode: 'DELIVERY_APPROACHING',
    name: L('Order left the factory', 'الطلب غادر المصنع', 'ההזמנה יצאה מהמפעל'),
    hint: L('The order is on the way.', 'الطلبية في الطريق.', 'ההזמנה בדרך.'),
    pushTitle: L('On the way', 'في الطريق إليك', 'בדרך אליכם'),
    pushBody: L('{number} left the factory.', '{number} غادرت المصنع.', '{number} יצאה מהמפעל.'),
  }),
  topic({
    code: 'delivery.completed',
    group: 'delivery',
    audiences: ['dealer', 'staff'],
    permission: 'delivery.read',
    entity: 'delivery',
    templateCode: 'DELIVERY_COMPLETED',
    name: L('Delivered', 'تم التسليم', 'נמסר'),
    hint: L('The order was delivered.', 'تم تسليم الطلبية.', 'ההזמנה נמסרה.'),
    pushTitle: L('Delivered', 'تم التسليم', 'נמסר'),
    pushBody: L('{number} was delivered.', 'تم تسليم {number}.', '{number} נמסרה.'),
  }),
  topic({
    code: 'delivery.failed',
    group: 'delivery',
    audiences: ['dealer', 'staff', 'worker'],
    permission: ['delivery.read', 'delivery.update'],
    urgency: 'high',
    entity: 'delivery',
    templateCode: 'DELIVERY_FAILED',
    name: L('Delivery failed', 'فشل التسليم', 'המשלוח נכשל'),
    hint: L('A delivery could not be completed.', 'تعذّر إتمام التسليم.', 'לא ניתן היה להשלים את המשלוח.'),
    pushTitle: L('Delivery failed', 'فشل التسليم', 'המשלוח נכשל'),
    pushBody: L('{number} could not be delivered.', 'تعذّر تسليم {number}.', 'לא ניתן היה למסור את {number}.'),
  }),
  topic({
    code: 'delivery.rescheduled',
    group: 'delivery',
    audiences: ['dealer', 'staff', 'worker'],
    permission: ['delivery.read', 'schedule.read'],
    entity: 'delivery',
    templateCode: 'DELIVERY_RESCHEDULED',
    name: L('Delivery rescheduled', 'إعادة جدولة التسليم', 'המשלוח נקבע מחדש'),
    hint: L('The delivery date was moved.', 'نُقل تاريخ التسليم.', 'תאריך המשלוח הוזז.'),
    pushTitle: L('Delivery rescheduled', 'أُعيد جدولة التسليم', 'המשלוח נקבע מחדש'),
    pushBody: L('{number} moved to {date}.', '{number} إلى {date}.', '{number} עברה ל-{date}.'),
  }),
  topic({
    code: 'delivery.receiptConfirmed',
    group: 'delivery',
    audiences: ['staff'],
    permission: 'delivery.read',
    entity: 'delivery',
    templateCode: 'DELIVERY_RECEIPT_CONFIRMED',
    name: L('Receipt confirmed', 'تأكيد الاستلام', 'אישור קבלה'),
    hint: L('The dealer confirmed receipt.', 'أكّد التاجر الاستلام.', 'הסוחר אישר קבלה.'),
    pushTitle: L('Receipt confirmed', 'تأكيد الاستلام', 'אישור קבלה'),
    pushBody: L('{number} was confirmed received.', 'أُكّد استلام {number}.', 'אושרה קבלת {number}.'),
  }),
  topic({
    code: 'inventory.received',
    group: 'inventory',
    audiences: ['staff'],
    permission: 'inventory.receive',
    defaultOn: false,
    entity: 'goodsReceipt',
    templateCode: 'INVENTORY_RECEIVED',
    name: L('Stock received', 'استلام مخزون', 'מלאי התקבל'),
    hint: L('A receive transaction was posted.', 'أُثبتت حركة استلام.', 'נרשמה תנועת קבלה.'),
    pushTitle: L('Stock received', 'استلام مخزون', 'מלאי התקבל'),
    pushBody: L('Receive posted for {number}.', 'أُثبت استلام {number}.', 'נרשמה קבלה עבור {number}.'),
  }),
  topic({
    code: 'inventory.issued',
    group: 'inventory',
    audiences: ['staff'],
    permission: 'inventory.issue',
    defaultOn: false,
    entity: 'inventoryItem',
    templateCode: 'INVENTORY_ISSUED',
    name: L('Stock issued', 'صرف مخزون', 'מלאי נופק'),
    hint: L('An issue transaction was posted.', 'أُثبتت حركة صرف.', 'נרשמה תנועת ניפוק.'),
    pushTitle: L('Stock issued', 'صرف مخزون', 'מלאי נופק'),
    pushBody: L('Issue posted for {sku}.', 'أُثبت صرف {sku}.', 'נרשם ניפוק עבור {sku}.'),
  }),
  topic({
    code: 'inventory.transferred',
    group: 'inventory',
    audiences: ['staff'],
    permission: 'inventory.transfer',
    defaultOn: false,
    entity: 'inventoryItem',
    templateCode: 'INVENTORY_TRANSFERRED',
    name: L('Stock transferred', 'تحويل مخزون', 'מלאי הועבר'),
    hint: L('A transfer was posted.', 'أُثبت تحويل.', 'נרשמה העברה.'),
    pushTitle: L('Stock transferred', 'تحويل مخزون', 'מלאי הועבר'),
    pushBody: L('Transfer posted for {sku}.', 'أُثبت تحويل {sku}.', 'נרשמה העברה עבור {sku}.'),
  }),
  topic({
    code: 'inventory.adjusted',
    group: 'inventory',
    audiences: ['staff'],
    permission: 'inventory.adjust',
    defaultOn: false,
    entity: 'inventoryItem',
    templateCode: 'INVENTORY_ADJUSTED',
    name: L('Stock adjusted', 'تسوية مخزون', 'מלאי הותאם'),
    hint: L('An adjustment was posted.', 'أُثبتت تسوية.', 'נרשמה התאמה.'),
    pushTitle: L('Stock adjusted', 'تسوية مخزون', 'מלאי הותאם'),
    pushBody: L('Adjustment posted for {sku}.', 'أُثبتت تسوية {sku}.', 'נרשמה התאמה עבור {sku}.'),
  }),
  topic({
    code: 'inventory.counted',
    group: 'inventory',
    audiences: ['staff'],
    permission: 'inventory.count',
    defaultOn: false,
    entity: 'inventoryItem',
    templateCode: 'INVENTORY_COUNTED',
    name: L('Count posted', 'إثبات الجرد', 'ספירה נרשמה'),
    hint: L('A stock count was posted.', 'أُثبت جرد.', 'נרשמה ספירת מלאי.'),
    pushTitle: L('Count posted', 'إثبات الجرد', 'ספירה נרשמה'),
    pushBody: L('Count posted for {sku}.', 'أُثبت جرد {sku}.', 'נרשמה ספירה עבור {sku}.'),
  }),
  topic({
    code: 'inventory.lowStock',
    group: 'inventory',
    audiences: ['staff'],
    permission: ['inventory.read', 'purchase-request.read'],
    urgency: 'high',
    entity: 'inventoryItem',
    templateCode: 'LOW_STOCK',
    name: L('Low stock', 'مخزون منخفض', 'מלאי נמוך'),
    hint: L('Items are at or below minimum.', 'أصناف عند الحد الأدنى أو دونه.', 'פריטים ברמת מינימום או מתחת.'),
    pushTitle: L('Low stock', 'مخزون منخفض', 'מלאי נמוך'),
    pushBody: L('{sku} is at or below minimum.', '{sku} عند الحد الأدنى أو دونه.', '{sku} ברמת מינימום או מתחת.'),
  }),
  topic({
    code: 'inventory.shortageBlockingProduction',
    group: 'inventory',
    audiences: ['staff'],
    permission: ['purchase-order.read', 'production-order.read'],
    urgency: 'high',
    entity: 'salesOrder',
    templateCode: 'MATERIAL_RISK',
    name: L('Shortage blocking production', 'نقص يوقف الإنتاج', 'מחסור שעוצר ייצור'),
    hint: L('A sales order is waiting on materials.', 'طلبية تنتظر المواد.', 'הזמנה ממתינה לחומרים.'),
    pushTitle: L('Materials blocking production', 'المواد توقف الإنتاج', 'חומרים עוצרים ייצור'),
    pushBody: L('{number} is waiting on materials.', '{number} تنتظر المواد.', '{number} ממתינה לחומרים.'),
  }),
  topic({
    code: 'inventory.finishedPosted',
    group: 'inventory',
    audiences: ['staff', 'worker'],
    permission: ['inventory.read', 'delivery.read'],
    entity: 'salesOrder',
    templateCode: 'FINISHED_GOODS_POSTED',
    name: L('Finished goods posted', 'إثبات بضاعة تامة', 'סחורה גמורה נרשמה'),
    hint: L('A finished lot was posted.', 'أُثبتت دفعة تامة.', 'נרשמה מנת סחורה גמורה.'),
    pushTitle: L('Finished goods posted', 'بضاعة تامة', 'סחורה גמורה'),
    pushBody: L('{number} finished goods are in stock.', 'بضاعة {number} التامة في المخزن.', 'הסחורה הגמורה של {number} במלאי.'),
  }),
  topic({
    code: 'inventory.correctionPending',
    group: 'inventory',
    audiences: ['staff'],
    permission: 'inventory.adjust',
    entity: 'inventoryItem',
    templateCode: 'INVENTORY_CORRECTION_PENDING',
    name: L('Correction pending', 'تصحيح بانتظارك', 'תיקון ממתין'),
    hint: L('An inventory correction needs attention.', 'تصحيح مخزون يحتاج مراجعة.', 'תיקון מלאי דורש תשומת לב.'),
    pushTitle: L('Stock correction', 'تصحيح مخزون', 'תיקון מלאי'),
    pushBody: L('{sku} has a pending correction.', '{sku} فيه تصحيح معلّق.', 'ל-{sku} תיקון ממתין.'),
  }),
  topic({
    code: 'pr.created',
    group: 'purchasing',
    audiences: ['staff'],
    permission: 'purchase-request.read',
    entity: 'purchaseRequest',
    templateCode: 'PR_CREATED',
    name: L('Purchase request created', 'إنشاء طلب شراء', 'נוצרה בקשת רכש'),
    hint: L('A purchase request was opened.', 'فُتح طلب شراء.', 'נפתחה בקשת רכש.'),
    pushTitle: L('Purchase request', 'طلب شراء', 'בקשת רכש'),
    pushBody: L('{number} was created.', 'أُنشئ {number}.', '{number} נוצרה.'),
  }),
  topic({
    code: 'pr.approved',
    group: 'purchasing',
    audiences: ['staff'],
    permission: 'purchase-request.read',
    entity: 'purchaseRequest',
    templateCode: 'PR_APPROVED',
    name: L('Purchase request approved', 'اعتماد طلب الشراء', 'בקשת רכש אושרה'),
    hint: L('A purchase request was approved.', 'اعتُمد طلب شراء.', 'בקשת רכש אושרה.'),
    pushTitle: L('Request approved', 'اعتُمد الطلب', 'הבקשה אושרה'),
    pushBody: L('{number} is approved.', 'اعتُمد {number}.', '{number} אושרה.'),
  }),
  topic({
    code: 'pr.rejected',
    group: 'purchasing',
    audiences: ['staff'],
    permission: 'purchase-request.read',
    entity: 'purchaseRequest',
    templateCode: 'PR_REJECTED',
    name: L('Purchase request rejected', 'رفض طلب الشراء', 'בקשת רכש נדחתה'),
    hint: L('A purchase request was rejected.', 'رُفض طلب شراء.', 'בקשת רכש נדחתה.'),
    pushTitle: L('Request rejected', 'رُفض الطلب', 'הבקשה נדחתה'),
    pushBody: L('{number} was rejected.', 'رُفض {number}.', '{number} נדחתה.'),
  }),
  topic({
    code: 'po.approved',
    group: 'purchasing',
    audiences: ['staff'],
    permission: 'purchase-order.read',
    entity: 'purchaseOrder',
    templateCode: 'PO_APPROVED',
    name: L('Purchase order approved', 'اعتماد أمر الشراء', 'הזמנת רכש אושרה'),
    hint: L('A purchase order was approved.', 'اعتُمد أمر شراء.', 'הזמנת רכש אושרה.'),
    pushTitle: L('PO approved', 'اعتُمد أمر الشراء', 'הזמנת רכש אושרה'),
    pushBody: L('{number} is approved.', 'اعتُمد {number}.', '{number} אושרה.'),
  }),
  topic({
    code: 'po.sent',
    group: 'purchasing',
    audiences: ['staff'],
    permission: 'purchase-order.read',
    entity: 'purchaseOrder',
    templateCode: 'PO_SENT',
    name: L('Purchase order sent', 'إرسال أمر الشراء', 'הזמנת רכש נשלחה'),
    hint: L('A purchase order was sent to the supplier.', 'أُرسل أمر شراء للمورّد.', 'הזמנת רכש נשלחה לספק.'),
    pushTitle: L('PO sent', 'أُرسل أمر الشراء', 'הזמנת רכש נשלחה'),
    pushBody: L('{number} was sent.', 'أُرسل {number}.', '{number} נשלחה.'),
  }),
  topic({
    code: 'po.partial',
    group: 'purchasing',
    audiences: ['staff'],
    permission: ['purchase-order.read', 'inventory.receive'],
    entity: 'purchaseOrder',
    templateCode: 'PO_PARTIAL',
    name: L('Purchase order partial', 'استلام جزئي لأمر الشراء', 'הזמנת רכש חלקית'),
    hint: L('A purchase order was partly received.', 'استُلم أمر شراء جزئياً.', 'הזמנת רכש התקבלה חלקית.'),
    pushTitle: L('Partial receive', 'استلام جزئي', 'קבלה חלקית'),
    pushBody: L('{number} was partly received.', 'استُلم {number} جزئياً.', '{number} התקבלה חלקית.'),
  }),
  topic({
    code: 'po.received',
    group: 'purchasing',
    audiences: ['staff'],
    permission: ['purchase-order.read', 'inventory.receive'],
    entity: 'purchaseOrder',
    templateCode: 'PO_RECEIVED',
    name: L('Purchase order received', 'استلام أمر الشراء', 'הזמנת רכש התקבלה'),
    hint: L('A purchase order was fully received.', 'استُلم أمر الشراء بالكامل.', 'הזמנת רכש התקבלה במלואה.'),
    pushTitle: L('PO received', 'استُلم أمر الشراء', 'הזמנת רכש התקבלה'),
    pushBody: L('{number} was received.', 'استُلم {number}.', '{number} התקבלה.'),
  }),
  topic({
    code: 'po.cancelled',
    group: 'purchasing',
    audiences: ['staff'],
    permission: 'purchase-order.read',
    entity: 'purchaseOrder',
    templateCode: 'PO_CANCELLED',
    name: L('Purchase order cancelled', 'إلغاء أمر الشراء', 'הזמנת רכש בוטלה'),
    hint: L('A purchase order was cancelled.', 'أُلغي أمر شراء.', 'הזמנת רכש בוטלה.'),
    pushTitle: L('PO cancelled', 'أُلغي أمر الشراء', 'הזמנת רכש בוטלה'),
    pushBody: L('{number} was cancelled.', 'أُلغي {number}.', '{number} בוטלה.'),
  }),
  topic({
    code: 'po.late',
    group: 'purchasing',
    audiences: ['staff'],
    permission: 'purchase-order.read',
    urgency: 'high',
    entity: 'purchaseOrder',
    templateCode: 'PO_LATE',
    name: L('Purchase order late', 'تأخر أمر الشراء', 'הזמנת רכש באיחור'),
    hint: L('A purchase order is past its expected date.', 'تجاوز أمر الشراء تاريخه المتوقع.', 'הזמנת רכש עברה את התאריך הצפוי.'),
    pushTitle: L('PO late', 'تأخر أمر الشراء', 'הזמנת רכש באיחור'),
    pushBody: L('{number} is late.', '{number} متأخر.', '{number} באיחור.'),
  }),
  topic({
    code: 'grn.posted',
    group: 'purchasing',
    audiences: ['staff'],
    permission: ['purchase-order.read', 'inventory.receive'],
    entity: 'goodsReceipt',
    templateCode: 'GRN_POSTED',
    name: L('Goods receipt posted', 'إثبات استلام بضاعة', 'קבלת סחורה נרשמה'),
    hint: L('A goods receipt was posted.', 'أُثبت استلام بضاعة.', 'נרשמה קבלת סחורה.'),
    pushTitle: L('Goods received', 'استلام بضاعة', 'סחורה התקבלה'),
    pushBody: L('Receipt {number} was posted.', 'أُثبت الإيصال {number}.', 'קבלה {number} נרשמה.'),
  }),
  topic({
    code: 'fabric.needsOrdering',
    group: 'purchasing',
    audiences: ['staff'],
    permission: ['fabric.procurement.read', 'production-order.read'],
    defaultOn: false,
    entity: 'fabricJob',
    templateCode: 'FABRIC_NEEDS_ORDERING',
    name: L('Fabric needs ordering', 'القماش يحتاج طلباً', 'בד דורש הזמנה'),
    hint: L('A fabric job still needs a supplier order.', 'مهمة قماش ما زالت تحتاج طلب مورّد.', 'משימת בד עדיין דורשת הזמנת ספק.'),
    pushTitle: L('Fabric to order', 'قماش للطلب', 'בד להזמנה'),
    pushBody: L('{number} needs fabric ordered.', '{number} تحتاج طلب قماش.', '{number} דורשת הזמנת בד.'),
  }),
  topic({
    code: 'fabric.awaitingSupplier',
    group: 'purchasing',
    audiences: ['staff'],
    permission: 'fabric.procurement.read',
    defaultOn: false,
    entity: 'fabricJob',
    templateCode: 'FABRIC_AWAITING_SUPPLIER',
    name: L('Fabric awaiting supplier', 'القماش بانتظار المورّد', 'בד ממתין לספק'),
    hint: L('Fabric was ordered and is waiting on the supplier.', 'طُلب القماش وهو بانتظار المورّد.', 'הבד הוזמן וממתין לספק.'),
    pushTitle: L('Awaiting fabric', 'بانتظار القماش', 'ממתינים לבד'),
    pushBody: L('{number} is waiting on fabric.', '{number} تنتظر القماش.', '{number} ממתינה לבד.'),
  }),
  topic({
    code: 'fabric.arrived',
    group: 'purchasing',
    audiences: ['staff'],
    permission: ['fabric.procurement.read', 'inventory.receive'],
    entity: 'fabricJob',
    templateCode: 'FABRIC_ARRIVED',
    name: L('Fabric arrived', 'وصول القماش', 'הבד הגיע'),
    hint: L('Fabric arrived at the factory.', 'وصل القماش إلى المصنع.', 'הבד הגיע למפעל.'),
    pushTitle: L('Fabric arrived', 'وصل القماش', 'הבד הגיע'),
    pushBody: L('Fabric for {number} arrived.', 'وصل قماش {number}.', 'הבד עבור {number} הגיע.'),
  }),
  topic({
    code: 'fabric.readyForPickup',
    group: 'purchasing',
    audiences: ['staff', 'worker'],
    permission: ['fabric.procurement.read', 'production-task.read'],
    entity: 'fabricJob',
    templateCode: 'FABRIC_READY_FOR_PICKUP',
    name: L('Fabric ready for pickup', 'القماش جاهز للأخذ', 'בד מוכן לאיסוף'),
    hint: L('Cut fabric is ready for the next stage.', 'القماش المقصوص جاهز للمرحلة التالية.', 'בד גזור מוכן לשלב הבא.'),
    pushTitle: L('Fabric ready', 'القماش جاهز', 'הבד מוכן'),
    pushBody: L('{number} · {sku} is ready.', '{number} · {sku} جاهز.', '{number} · {sku} מוכן.'),
  }),
  topic({
    code: 'fabric.unavailable',
    group: 'purchasing',
    audiences: ['staff'],
    permission: ['fabric.procurement.read', 'production-order.read'],
    urgency: 'high',
    entity: 'fabricJob',
    templateCode: 'FABRIC_UNAVAILABLE',
    name: L('Fabric unavailable', 'القماش غير متوفر', 'בד אינו זמין'),
    hint: L('Needed fabric is not available.', 'القماش المطلوب غير متوفر.', 'הבד הנדרש אינו זמין.'),
    pushTitle: L('Fabric unavailable', 'القماش غير متوفر', 'בד אינו זמין'),
    pushBody: L('{number} is waiting on fabric.', '{number} تنتظر القماش.', '{number} ממתינה לבד.'),
  }),
  topic({
    code: 'return.submitted',
    group: 'returns',
    audiences: ['staff'],
    permission: ['return.read', 'sales-order.read'],
    entity: 'returnRequest',
    templateCode: 'RETURN_SUBMITTED',
    name: L('Return submitted', 'تقديم مرتجع', 'החזרה הוגשה'),
    hint: L('A dealer opened a return.', 'فتح التاجر مرتجعاً.', 'הסוחר פתח החזרה.'),
    pushTitle: L('New return', 'مرتجع جديد', 'החזרה חדשה'),
    pushBody: L('{number} was submitted.', 'قُدّم {number}.', '{number} הוגשה.'),
  }),
  topic({
    code: 'return.approved',
    group: 'returns',
    audiences: ['dealer', 'staff'],
    permission: 'return.read',
    entity: 'returnRequest',
    templateCode: 'RETURN_APPROVED',
    name: L('Return approved', 'قبول المرتجع', 'החזרה אושרה'),
    hint: L('A return request was approved.', 'قُبل طلب المرتجع.', 'בקשת החזרה אושרה.'),
    pushTitle: L('Return approved', 'قُبل المرتجع', 'החזרה אושרה'),
    pushBody: L('{number} was approved.', 'قُبل {number}.', '{number} אושרה.'),
  }),
  topic({
    code: 'return.rejected',
    group: 'returns',
    audiences: ['dealer', 'staff'],
    permission: 'return.read',
    entity: 'returnRequest',
    templateCode: 'RETURN_REJECTED',
    name: L('Return rejected', 'رفض المرتجع', 'החזרה נדחתה'),
    hint: L('A return request was rejected.', 'رُفض طلب المرتجع.', 'בקשת החזרה נדחתה.'),
    pushTitle: L('Return rejected', 'رُفض المرتجع', 'החזרה נדחתה'),
    pushBody: L('{number} was rejected.', 'رُفض {number}.', '{number} נדחתה.'),
  }),
  topic({
    code: 'return.needInfo',
    group: 'returns',
    audiences: ['dealer', 'staff'],
    permission: 'return.read',
    entity: 'returnRequest',
    templateCode: 'RETURN_NEED_INFO',
    name: L('Return needs information', 'المرتجع يحتاج معلومات', 'ההחזרה דורשת מידע'),
    hint: L('The factory asked for more return details.', 'طلب المصنع تفاصيل إضافية للمرتجع.', 'המפעל ביקש פרטים נוספים להחזרה.'),
    pushTitle: L('Return needs a reply', 'المرتجع بانتظار رد', 'ההחזרה ממתינה לתשובה'),
    pushBody: L('{number} needs more information.', '{number} يحتاج معلومات إضافية.', '{number} דורשת מידע נוסף.'),
  }),
  topic({
    code: 'return.received',
    group: 'returns',
    audiences: ['dealer', 'staff'],
    permission: 'return.read',
    entity: 'returnRequest',
    templateCode: 'RETURN_RECEIVED',
    name: L('Return received', 'وصول المرتجع', 'ההחזרה התקבלה'),
    hint: L('The return arrived at the factory.', 'وصل المرتجع إلى المصنع.', 'ההחזרה הגיעה למפעל.'),
    pushTitle: L('Return received', 'وصل المرتجع', 'ההחזרה התקבלה'),
    pushBody: L('{number} arrived at the factory.', 'وصل {number} إلى المصنع.', '{number} הגיעה למפעל.'),
  }),
  topic({
    code: 'return.decision',
    group: 'returns',
    audiences: ['dealer', 'staff'],
    permission: 'return.read',
    entity: 'returnRequest',
    templateCode: 'RETURN_DECISION',
    name: L('Return decision', 'قرار المرتجع', 'החלטת החזרה'),
    hint: L('The factory recorded a return decision.', 'سجّل المصنع قراراً على المرتجع.', 'המפעל רשם החלטה על ההחזרה.'),
    pushTitle: L('Return decision', 'قرار المرتجع', 'החלטת החזרה'),
    pushBody: L('A decision was recorded on {number}.', 'سُجّل قرار على {number}.', 'נרשמה החלטה על {number}.'),
  }),
  topic({
    code: 'return.workStarted',
    group: 'returns',
    audiences: ['dealer', 'staff'],
    permission: 'return.read',
    entity: 'returnRequest',
    templateCode: 'RETURN_WORK_STARTED',
    name: L('Return work started', 'بدء عمل المرتجع', 'עבודת החזרה החלה'),
    hint: L('Factory work started on the return.', 'بدأ المصنع العمل على المرتجع.', 'עבודת המפעל על ההחזרה החלה.'),
    pushTitle: L('Return work started', 'بدأ عمل المرتجع', 'עבודת החזרה החלה'),
    pushBody: L('Work started on {number}.', 'بدأ العمل على {number}.', 'העבודה על {number} החלה.'),
  }),
  topic({
    code: 'return.ready',
    group: 'returns',
    audiences: ['dealer', 'staff'],
    permission: 'return.read',
    entity: 'returnRequest',
    templateCode: 'RETURN_READY',
    name: L('Return ready', 'المرتجع جاهز', 'ההחזרה מוכנה'),
    hint: L('The return is ready to ship back.', 'المرتجع جاهز للإعادة.', 'ההחזרה מוכנה למשלוח חזרה.'),
    pushTitle: L('Return ready', 'المرتجع جاهز', 'ההחזרה מוכנה'),
    pushBody: L('{number} is ready to ship back.', '{number} جاهز للإعادة.', '{number} מוכנה למשלוח חזרה.'),
  }),
  topic({
    code: 'return.reshipScheduled',
    group: 'returns',
    audiences: ['dealer', 'staff'],
    permission: 'return.read',
    entity: 'returnRequest',
    templateCode: 'RETURN_RESHIP_SCHEDULED',
    name: L('Return shipment scheduled', 'جدولة إعادة المرتجع', 'משלוח החזרה נקבע'),
    hint: L('A return shipment was scheduled.', 'جُدولت شحنة إعادة المرتجع.', 'נקבע משלוח החזרה.'),
    pushTitle: L('Return shipment scheduled', 'جُدولت إعادة المرتجع', 'משלוח החזרה נקבע'),
    pushBody: L('{number} is scheduled ({delivery}).', 'جُدول {number} ({delivery}).', '{number} נקבעה ({delivery}).'),
  }),
  topic({
    code: 'return.delivered',
    group: 'returns',
    audiences: ['dealer', 'staff'],
    permission: 'return.read',
    entity: 'returnRequest',
    templateCode: 'RETURN_DELIVERED',
    name: L('Return delivered', 'تسليم المرتجع', 'ההחזרה נמסרה'),
    hint: L('The return was delivered back.', 'أُعيد تسليم المرتجع.', 'ההחזרה נמסרה חזרה.'),
    pushTitle: L('Return delivered', 'وصل المرتجع', 'ההחזרה נמסרה'),
    pushBody: L('{number} was delivered.', 'تم تسليم {number}.', '{number} נמסרה.'),
  }),
  topic({
    code: 'return.chargeProposed',
    group: 'returns',
    audiences: ['dealer', 'staff'],
    permission: ['return.read', 'invoice.read'],
    entity: 'returnRequest',
    templateCode: 'RETURN_CHARGE_PROPOSED',
    name: L('Return charge proposed', 'اقتراح مبلغ مرتجع', 'הוצע חיוב החזרה'),
    hint: L('A return charge is waiting for confirmation.', 'مبلغ مرتجع بانتظار التأكيد.', 'חיוב החזרה ממתין לאישור.'),
    pushTitle: L('Return charge to confirm', 'مبلغ مرتجع للتأكيد', 'חיוב החזרה לאישור'),
    pushBody: L('{number} has a charge to confirm.', '{number} فيه مبلغ بانتظار تأكيدك.', 'ל-{number} חיוב שממתין לאישור.'),
  }),
  topic({
    code: 'return.charged',
    group: 'returns',
    audiences: ['dealer', 'staff'],
    permission: ['return.read', 'invoice.read'],
    entity: 'returnRequest',
    templateCode: 'RETURN_CHARGED',
    name: L('Return invoice created', 'فاتورة مرتجع', 'נוצרה חשבונית החזרה'),
    hint: L('A return invoice was created.', 'أُنشئت فاتورة مرتجع.', 'נוצרה חשבונית החזרה.'),
    pushTitle: L('Return invoice', 'فاتورة مرتجع', 'חשבונית החזרה'),
    pushBody: L('Invoice {invoice} for {number}.', 'الفاتورة {invoice} للمرتجع {number}.', 'חשבונית {invoice} עבור {number}.'),
  }),
  topic({
    code: 'return.chargeRejected',
    group: 'returns',
    audiences: ['staff'],
    permission: ['return.read', 'invoice.read'],
    entity: 'returnRequest',
    templateCode: 'RETURN_CHARGE_REJECTED',
    name: L('Return charge rejected', 'رفض مبلغ المرتجع', 'חיוב ההחזרה נדחה'),
    hint: L('The dealer rejected a return charge.', 'رفض التاجر مبلغ المرتجع.', 'הסוחר דחה חיוב החזרה.'),
    pushTitle: L('Charge rejected', 'رُفض المبلغ', 'החיוב נדחה'),
    pushBody: L('The dealer rejected the charge on {number}.', 'رفض التاجر مبلغ {number}.', 'הסוחר דחה את החיוב על {number}.'),
  }),
  topic({
    code: 'invoice.created',
    group: 'finance',
    audiences: ['dealer', 'staff'],
    permission: 'invoice.read',
    entity: 'invoice',
    templateCode: 'INVOICE_CREATED',
    name: L('Invoice created', 'إنشاء فاتورة', 'נוצרה חשבונית'),
    hint: L('A new invoice was issued.', 'أُصدرت فاتورة جديدة.', 'הוצאה חשבונית חדשה.'),
    pushTitle: L('New invoice', 'فاتورة جديدة', 'חשבונית חדשה'),
    pushBody: L('Invoice {number} is ready.', 'الفاتورة {number} جاهزة.', 'חשבונית {number} מוכנה.'),
  }),
  topic({
    code: 'invoice.overdue',
    group: 'finance',
    audiences: ['dealer', 'staff'],
    permission: 'invoice.read',
    urgency: 'high',
    entity: 'invoice',
    templateCode: 'INVOICE_OVERDUE',
    name: L('Invoice overdue', 'فاتورة متأخرة', 'חשבונית באיחור'),
    hint: L('An invoice is past due.', 'فاتورة تجاوزت استحقاقها.', 'חשבונית עברה את מועד התשלום.'),
    pushTitle: L('Invoice overdue', 'فاتورة متأخرة', 'חשבונית באיחור'),
    pushBody: L('{number} is overdue.', '{number} متأخرة.', '{number} באיחור.'),
  }),
  topic({
    code: 'invoice.voided',
    group: 'finance',
    audiences: ['dealer', 'staff'],
    permission: 'invoice.read',
    entity: 'invoice',
    templateCode: 'INVOICE_VOIDED',
    name: L('Invoice voided', 'إلغاء فاتورة', 'חשבונית בוטלה'),
    hint: L('An invoice was voided.', 'أُلغيت فاتورة.', 'חשבונית בוטלה.'),
    pushTitle: L('Invoice voided', 'أُلغيت الفاتورة', 'חשבונית בוטלה'),
    pushBody: L('{number} was voided.', 'أُلغي {number}.', '{number} בוטלה.'),
  }),
  topic({
    code: 'payment.received',
    group: 'finance',
    audiences: ['dealer', 'staff'],
    permission: 'payment.read',
    entity: 'payment',
    templateCode: 'PAYMENT_RECEIVED',
    name: L('Payment received', 'استلام دفعة', 'תשלום התקבל'),
    hint: L('A payment was recorded.', 'سُجّلت دفعة.', 'נרשם תשלום.'),
    pushTitle: L('Payment received', 'استلام دفعة', 'תשלום התקבל'),
    pushBody: L('{invoice} has a new payment.', 'دفعة جديدة على {invoice}.', 'תשלום חדש עבור {invoice}.'),
  }),
  topic({
    code: 'payment.failed',
    group: 'finance',
    audiences: ['dealer', 'staff'],
    permission: 'payment.read',
    urgency: 'high',
    entity: 'payment',
    templateCode: 'PAYMENT_FAILED',
    name: L('Payment failed', 'فشل الدفعة', 'התשלום נכשל'),
    hint: L('A payment could not be recorded.', 'تعذّر تسجيل دفعة.', 'לא ניתן היה לרשום תשלום.'),
    pushTitle: L('Payment failed', 'فشل الدفعة', 'התשלום נכשל'),
    pushBody: L('A payment on {number} failed.', 'فشلت دفعة على {number}.', 'תשלום על {number} נכשל.'),
  }),
  topic({
    code: 'schedule.awaitingApproval',
    group: 'schedule',
    audiences: ['staff'],
    permission: 'schedule.approve',
    defaultOn: false,
    entity: 'schedule',
    templateCode: 'SCHEDULE_AWAITING_APPROVAL',
    name: L('Schedule awaiting approval', 'جدول بانتظار الموافقة', 'לוח ממתין לאישור'),
    hint: L('A production schedule needs approval.', 'جدول إنتاج ينتظر موافقتك.', 'לוח ייצור ממתין לאישורכם.'),
    pushTitle: L('Schedule to approve', 'جدول للموافقة', 'לוח לאישור'),
    pushBody: L('{number} is waiting for approval.', '{number} بانتظار الموافقة.', '{number} ממתינה לאישור.'),
  }),
  topic({
    code: 'schedule.atRisk',
    group: 'schedule',
    audiences: ['staff'],
    permission: 'schedule.manage',
    urgency: 'high',
    entity: 'schedule',
    templateCode: 'SCHEDULE_AT_RISK',
    name: L('Schedule at risk', 'جدول معرّض للتأخير', 'לוח בסיכון'),
    hint: L('A production schedule is at risk of delay.', 'جدول الإنتاج معرّض للتأخير.', 'לוח הייצור בסיכון לעיכוב.'),
    pushTitle: L('Schedule at risk', 'جدول معرّض للتأخير', 'לוח בסיכון'),
    pushBody: L('{number} is at risk.', '{number} معرّض للتأخير.', '{number} בסיכון.'),
  }),
  topic({
    code: 'schedule.conflict',
    group: 'schedule',
    audiences: ['staff'],
    permission: 'schedule.manage',
    urgency: 'high',
    entity: 'schedule',
    templateCode: 'SCHEDULE_CONFLICT',
    name: L('Schedule conflict', 'تعارض في الجدول', 'התנגשות בלוח'),
    hint: L('A scheduling conflict was detected.', 'اكتُشف تعارض في الجدول.', 'זוהתה התנגשות בלוח.'),
    pushTitle: L('Schedule conflict', 'تعارض في الجدول', 'התנגשות בלוח'),
    pushBody: L('{number} has a conflict.', '{number} فيه تعارض.', 'ל-{number} התנגשות.'),
  }),
  topic({
    code: 'schedule.replanProposed',
    group: 'schedule',
    audiences: ['staff'],
    permission: 'schedule.manage',
    defaultOn: false,
    entity: 'schedule',
    templateCode: 'SCHEDULE_REPLAN_PROPOSED',
    name: L('Replan proposed', 'اقتراح إعادة جدولة', 'הוצעה תזמון מחדש'),
    hint: L('A schedule replan is waiting for review.', 'إعادة جدولة بانتظار المراجعة.', 'תזמון מחדש ממתין לבדיקה.'),
    pushTitle: L('Replan proposed', 'اقتراح إعادة جدولة', 'הוצעה תזמון מחדש'),
    pushBody: L('{number} has a new plan to review.', '{number} فيه خطة جديدة للمراجعة.', 'ל-{number} תוכנית חדשה לבדיקה.'),
  }),
  topic({
    code: 'dealerDate.changeRequest',
    group: 'schedule',
    audiences: ['staff'],
    permission: 'schedule.manage',
    entity: 'salesOrder',
    templateCode: 'DEALER_DATE_CHANGE_REQUEST',
    name: L('Dealer date change', 'طلب تغيير تاريخ التاجر', 'בקשת שינוי תאריך מהסוחר'),
    hint: L('A dealer asked to change a delivery date.', 'طلب التاجر تغيير تاريخ التسليم.', 'הסוחר ביקש לשנות תאריך אספקה.'),
    pushTitle: L('Date change requested', 'طلب تغيير التاريخ', 'בקשת שינוי תאריך'),
    pushBody: L('{number} → {date}.', '{number} → {date}.', '{number} → {date}.'),
  }),
  topic({
    code: 'dealerDate.updated',
    group: 'schedule',
    audiences: ['staff'],
    permission: 'schedule.read',
    entity: 'salesOrder',
    templateCode: 'DEALER_DATE_UPDATED',
    name: L('Preferred date updated', 'تحديث التاريخ المفضل', 'תאריך מועדף עודכן'),
    hint: L('The dealer updated a preferred delivery date.', 'حدّث التاجر تاريخ التسليم المفضل.', 'הסוחר עדכן תאריך אספקה מועדף.'),
    pushTitle: L('Preferred date updated', 'تحديث التاريخ المفضل', 'תאריך מועדף עודכן'),
    pushBody: L('{number} → {date}.', '{number} → {date}.', '{number} → {date}.'),
  }),
  topic({
    code: 'user.invited',
    group: 'people',
    audiences: ['staff'],
    permission: 'user.manage',
    entity: 'user',
    templateCode: 'USER_INVITED',
    name: L('New staff account', 'حساب موظف جديد', 'חשבון עובד חדש'),
    hint: L('A new staff account was created.', 'تم إنشاء حساب موظف جديد.', 'נוצר חשבון עובד חדש.'),
    pushTitle: L('New staff account', 'حساب موظف جديد', 'חשבון עובד חדש'),
    pushBody: L('A new staff account was created.', 'تم إنشاء حساب موظف جديد.', 'נוצר חשבון עובד חדש.'),
  }),
  topic({
    code: 'user.deactivated',
    group: 'people',
    audiences: ['staff'],
    permission: 'user.manage',
    entity: 'user',
    templateCode: 'USER_DEACTIVATED',
    name: L('Access changed', 'تغيّر الوصول', 'הגישה השתנתה'),
    hint: L(
      'Workspace access was updated.',
      'تم تحديث الوصول إلى مساحة العمل.',
      'הגישה לסביבת העבודה עודכנה.',
    ),
    pushTitle: L('Access changed', 'تغيّر الوصول', 'הגישה השתנתה'),
    pushBody: L(
      'Your Maher ERP staff access was updated.',
      'تم تحديث صلاحية وصولك إلى نظام ماهر.',
      'הגישה שלכם למערכת מاهر עודכנה.',
    ),
  }),
  topic({
    code: 'user.roleChanged',
    group: 'people',
    audiences: ['staff'],
    permission: 'user.manage',
    entity: 'user',
    templateCode: 'USER_ROLE_CHANGED',
    name: L('Access changed', 'تغيّر الوصول', 'הגישה השתנתה'),
    hint: L(
      'A staff type or role was updated.',
      'تم تحديث نوع الموظف أو الدور.',
      'סוג המשרה או התפקיד עודכן.',
    ),
    pushTitle: L('Access changed', 'تغيّر الوصول', 'הגישה השתנתה'),
    pushBody: L(
      'Your Maher ERP staff access was updated.',
      'تم تحديث صلاحية وصولك إلى نظام ماهر.',
      'הגישה שלכם למערכת מاهر עודכנה.',
    ),
  }),
];

const byCode = new Map(TOPICS_LIST.map((row) => [row.code, row]));
const byTemplate = new Map(TOPICS_LIST.map((row) => [row.templateCode, row.code]));

export const TOPICS: readonly TopicDefinition[] = TOPICS_LIST;

export function getTopic(code: string | null | undefined): TopicDefinition | undefined {
  if (!code) return undefined;
  return byCode.get(code);
}

export function topicFromTemplateCode(templateCode: string | null | undefined): TopicDefinition | undefined {
  if (!templateCode) return undefined;
  const code = byTemplate.get(templateCode);
  return code ? byCode.get(code) : undefined;
}

export function topicsForGroup(group: TopicGroup): TopicDefinition[] {
  return TOPICS_LIST.filter((row) => row.group === group);
}

export const TOPIC_CODES = TOPICS_LIST.map((row) => row.code);
