import type { WorkerHomePayload } from './api';

export const workerHomeSuccessFixture: WorkerHomePayload = {
  completedTodayCount: 3,
  unreadNotifications: 2,
  urgentTask: {
    id: 't-urgent',
    productionOrderId: 'po-urgent',
    number: 'PT-1042',
    name: 'Upholstery',
    nameEn: 'Upholstery',
    nameAr: 'التنجيد',
    priority: 'URGENT',
    status: 'IN_PROGRESS',
    orderNumber: 'SO-DEMO-0002',
    productTitle: 'Lobby Sofa',
    productNameEn: 'Lobby Sofa',
    productNameAr: 'كنبة اللوبي',
    imageUrl: null,
    deadline: '2026-08-05T17:00:00.000Z',
    estimatedMinutes: 90,
  },
  todaysTasks: [
    {
      id: 't2',
      productionOrderId: 'po-t2',
      number: 'PT-1043',
      name: 'Frame assembly',
      nameEn: 'Frame assembly',
      nameAr: 'تجميع الهيكل',
      priority: 'HIGH',
      status: 'READY',
      orderNumber: 'SO-DEMO-0004',
      productTitle: 'Dining Chairs',
      productNameEn: 'Dining Chairs',
      productNameAr: 'كراسي سفرة',
      imageUrl: null,
      deadline: '2026-08-05T15:30:00.000Z',
      estimatedMinutes: 120,
    },
    {
      id: 't3',
      productionOrderId: 'po-t3',
      number: 'PT-1044',
      name: 'Sanding',
      nameEn: 'Sanding',
      nameAr: 'الصنفرة',
      priority: 'NORMAL',
      status: 'NOT_STARTED',
      orderNumber: 'SO-DEMO-0005',
      productTitle: 'Oak Desk',
      productNameEn: 'Oak Desk',
      productNameAr: 'مكتب سنديان',
      imageUrl: null,
      deadline: null,
      estimatedMinutes: 45,
    },
  ],
  notifications: [
    {
      id: 'n1',
      title: 'New task assigned',
      titleEn: 'New task assigned',
      titleAr: 'تم إسناد مهمة جديدة',
      body: 'PT-1042 — Lobby Sofa',
      bodyEn: 'PT-1042 — Lobby Sofa',
      bodyAr: 'PT-1042 — كنبة اللوبي',
      createdAt: '2026-08-05T12:00:00.000Z',
      readAt: null,
    },
    {
      id: 'n2',
      title: 'Deadline approaching',
      titleEn: 'Deadline approaching',
      titleAr: 'اقتراب الموعد النهائي',
      body: 'SO-DEMO-0004 due this afternoon',
      bodyEn: 'SO-DEMO-0004 due this afternoon',
      bodyAr: 'SO-DEMO-0004 مستحق بعد الظهر',
      createdAt: '2026-08-05T11:00:00.000Z',
      readAt: null,
    },
  ],
  generatedAt: '2026-08-05T12:30:00.000Z',
};

export const workerHomeEmptyFixture: WorkerHomePayload = {
  completedTodayCount: 0,
  unreadNotifications: 0,
  urgentTask: null,
  todaysTasks: [],
  notifications: [],
  generatedAt: '2026-08-05T12:30:00.000Z',
};
