import type { SalesOrderDetail } from './api';

export const adminOrderDetailFixture: SalesOrderDetail = {
  id: 'so1',
  number: 'ORD-1258',
  status: 'IN_PRODUCTION',
  priority: 'HIGH',
  title: 'Lobby Sofa',
  imageUrl: null,
  notes: 'Rush for hotel lobby install',
  externalOrderNumber: 'PO-441',
  deliveryAddress: 'Amman · Abdoun',
  requiredDeliveryDate: '2026-08-20T00:00:00.000Z',
  projectName: 'Grand Hotel Lobby',
  progressPercent: 55,
  currentStage: {
    code: 'UPHOLSTERY',
    nameEn: 'Upholstery',
    nameAr: 'تنجيد',
    nameHe: 'ריפוד',
  },
  sellerPrice: 12000,
  productionPrice: 7800,
  manufacturingCost: 7800,
  profit: 4200,
  costBreakdown: {
    fabricQty: 12,
    fabricCost: 1200,
    woodQty: 4,
    woodCost: 2400,
    foamQty: 6,
    foamCost: 900,
    accessoriesQty: 2,
    accessoriesCost: 300,
  },
  assignedEmployee: { id: 'w1', name: 'Ali Hassan' },
  customer: {
    id: 'c1',
    name: 'Ahmed Traders',
    nameEn: 'Ahmed Traders',
    phone: '+962 6 555 0100',
    fax: '+962 6 555 0101',
  },
  customerRequest: {
    notes: 'Match lobby carpet tone',
    source: 'PORTAL',
    projectName: 'Grand Hotel Lobby',
    externalOrderNumber: 'PO-441',
    endCustomerName: 'Grand Hotel',
    endCustomerPhone: '+962 7 9000 0000',
    endCustomerFax: '+962 6 9000 0001',
    deliveryAddress: 'Amman · Abdoun',
    requiredDeliveryDate: '2026-08-20T00:00:00.000Z',
    translatedText: 'Match lobby carpet tone',
    originalText: 'طابق لون سجاد الردهة',
    detectedLanguage: 'ar',
    targetLanguage: 'en',
    items: [
      {
        id: 'i1',
        productName: 'Lobby Sofa',
        description: '3-seater with oak legs',
        fabricType: 'Linen',
        fabricColor: 'Sand',
        fabricCode: 'LN-12',
        woodType: 'Oak',
        foamDensity: '35kg',
        finish: 'Matte',
        width: 220,
        height: 85,
        depth: 95,
        quantity: 2,
        notes: 'Extra lumbar support',
      },
    ],
    documents: [
      {
        id: 'd1',
        fileName: 'sketch.png',
        mimeType: 'image/png',
      },
    ],
  },
  orderedItems: [
    {
      id: 'i1',
      productName: 'Lobby Sofa',
      quantity: 2,
    },
  ],
  productionOrders: [
    {
      id: 'po1',
      number: 'PO-1',
      status: 'IN_PROGRESS',
      progressPercent: 55,
      stages: [
        {
          code: 'MATERIAL_PREP',
          nameEn: 'Material preparation',
          sortOrder: 1,
          dependsOnCodes: [],
          status: 'COMPLETED',
          progressPercent: 100,
        },
        {
          code: 'CARPENTRY',
          nameEn: 'Carpentry',
          sortOrder: 2,
          dependsOnCodes: ['MATERIAL_PREP'],
          status: 'COMPLETED',
          progressPercent: 100,
        },
        {
          code: 'PAINTING',
          nameEn: 'Painting',
          sortOrder: 3,
          dependsOnCodes: ['MATERIAL_PREP'],
          status: 'IN_PROGRESS',
          progressPercent: 40,
        },
        {
          code: 'UPHOLSTERY',
          nameEn: 'Upholstery',
          sortOrder: 4,
          dependsOnCodes: ['CARPENTRY'],
          status: 'PENDING',
          progressPercent: 0,
        },
        {
          code: 'ASSEMBLY',
          nameEn: 'Assembly',
          sortOrder: 5,
          dependsOnCodes: ['CARPENTRY', 'PAINTING', 'UPHOLSTERY'],
          status: 'PENDING',
          progressPercent: 0,
        },
      ],
      photos: [],
    },
  ],
  invoices: [
    { id: 'inv1', number: 'INV-900', status: 'ISSUED', total: 12000, outstandingAmount: 4000 },
  ],
  deliveries: [
    {
      id: 'del1',
      number: 'DEL-1',
      status: 'SCHEDULED',
      deliveryDate: '2026-08-22T00:00:00.000Z',
    },
  ],
  returns: [],
};

export const adminDraftOrderDetailFixture: SalesOrderDetail = {
  ...adminOrderDetailFixture,
  id: 'so-draft',
  number: 'ORD-DRAFT',
  status: 'DRAFT',
  progressPercent: 0,
  productionOrders: [],
  invoices: [],
  deliveries: [],
};

export const dealerOrderDetailFixture: SalesOrderDetail = {
  id: 'so1',
  number: 'ORD-1258',
  status: 'IN_PRODUCTION',
  priority: 'HIGH',
  title: 'Lobby Sofa',
  imageUrl: null,
  notes: 'Rush for hotel lobby install',
  externalOrderNumber: 'PO-441',
  deliveryAddress: 'Amman · Abdoun',
  requiredDeliveryDate: '2026-08-20T00:00:00.000Z',
  progressPercent: 40,
  progressLabel: 'In progress',
  sellerPrice: 12000,
  customer: { id: 'c1', name: 'Nile Interiors', nameEn: 'Nile Interiors' },
  customerRequest: {
    notes: 'Match lobby carpet tone',
    externalOrderNumber: 'PO-441',
    items: [
      {
        id: 'i1',
        productName: 'Lobby Sofa',
        fabricType: 'Linen',
        fabricColor: 'Sand',
        fabricCode: 'LN-12',
        quantity: 2,
      },
    ],
    documents: [
      {
        id: 'd1',
        fileName: 'sketch.png',
        mimeType: 'image/png',
      },
    ],
  },
  productionOrders: [
    {
      id: 'po1',
      number: 'PO-1',
      status: 'IN_PROGRESS',
      progressPercent: 40,
      progressLabel: 'In progress',
      stages: [
        {
          code: 'CUT',
          nameEn: 'Cutting',
          nameAr: 'قص',
          sortOrder: 1,
          dependsOnCodes: [],
          status: 'COMPLETED',
          progressPercent: 100,
        },
        {
          code: 'UPHOLSTERY',
          nameEn: 'Upholstery',
          nameAr: 'تنجيد',
          sortOrder: 2,
          dependsOnCodes: ['CUT'],
          status: 'IN_PROGRESS',
          progressPercent: 40,
        },
      ],
      photos: [],
    },
  ],
  invoices: [
    { id: 'inv1', number: 'INV-900', status: 'ISSUED', total: 12000, outstandingAmount: 4000 },
  ],
  returns: [
    {
      id: 'ret1',
      number: 'RET-1',
      approvalStatus: 'PENDING',
      reason: 'Scratch on arm',
    },
  ],
};
